In [1]:
import emoji
import nltk
import numpy as np
import pandas as pd
import re

from nltk.tokenize import TweetTokenizer
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer

Change the path for the csv ***HERE*** accordingly to load/save

In [2]:
IN_CSV = "../../data/twitter_training.csv"
OUT_CSV = '../../data/output_file.csv'

TITLES = ["id", "entity", "sentiment", "text"]

In [3]:
df = pd.read_csv(IN_CSV, names=TITLES).astype(str)

In [4]:
df.head()

,id,entity,sentiment,text
0,2401,Borderlands,Positive,im getting on borderlands and i will murder yo...
1,2401,Borderlands,Positive,I am coming to the borders and I will kill you...
2,2401,Borderlands,Positive,im getting on borderlands and i will kill you ...
3,2401,Borderlands,Positive,im coming on borderlands and i will murder you...
4,2401,Borderlands,Positive,im getting on borderlands 2 and i will murder ...

In [5]:
tokenizer = TweetTokenizer()

Bingxi: Note for myself that twitter usernames are not case sensitive.

In [6]:
def load_emoticon_dict(dict_pth="../../data/emoji/emoticon.txt"):
    emoticon_dict = {}

    with open(dict_pth, "r", encoding="utf-8") as f:
        lines = [line.strip() for line in f]

    i = 0
    while i < len(lines):
        if lines[i] == "":
            i += 1
            continue

        emoticons = lines[i].split()
        meaning = lines[i + 1].upper()
        
        meaning = re.sub(r",", " ", meaning)
        meaning = re.sub(r"\s+", "_", meaning)
        
        for emo in emoticons:
            emo = re.sub(r"&nbsp;", " ", emo)
            emoticon_dict[emo] = meaning

        i += 3

    return emoticon_dict

In [7]:
emoticon_dict = load_emoticon_dict()

In [8]:
print(emoticon_dict)

{':‑)': 'SMILEY', ':)': 'SMILEY', ':-]': 'SMILEY', ':]': 'SMILEY', ':->': 'SMILEY', ':>': 'SMILEY', '8-)': 'SMILEY', '8)': 'SMILEY', ':-}': 'SMILEY', ':}': 'SMILEY', ':^)': 'SMILEY', '=]': 'SMILEY', '=)': 'SMILEY', ':‑D': 'BIG_GRIN', ':D': 'BIG_GRIN', '8‑D': 'BIG_GRIN', '8D': 'BIG_GRIN', '=D': 'BIG_GRIN', '=3': 'PLAYFUL_CUTE_CAT', 'B^D': 'BIG_GRIN', 'c:': 'BIG_GRIN', 'C:': 'BIG_GRIN', 'x‑D': 'LAUGHING', 'xD': 'LAUGHING', 'X‑D': 'LAUGHING', 'XD': 'LAUGHING', ':-))': 'DOUBLE_CHIN', ':))': 'DOUBLE_CHIN', ':‑(': 'FROWN_SAD', ':(': 'FROWN_SAD', ':‑c': 'FROWN_SAD', ':c': 'FROWN_SAD', ':‑<': 'FROWN_SAD', ':<': 'FROWN_SAD', ':‑[': 'FROWN_SAD', ':[': 'FROWN_SAD', ':-||': 'FROWN_SAD', ':{': 'FROWN_SAD', ':@': 'FROWN_SAD', ';(': 'FROWN_SAD', ":'‑(": 'CRYING', ":'(": 'CRYING', ':=(': 'CRYING', ":'‑)": 'TEARS_OF_HAPPINESS', ":')": 'TEARS_OF_HAPPINESS', ':"D': 'TEARS_OF_HAPPINESS', '>:(': 'ANGRY', '>:[': 'ANGRY', "D‑':": 'HORROR', 'D:<': 'DISGUST', 'D;': 'SADNESS', 'D:': 'DISMAY', 'D8': 'DISMAY', 'D=': 'DISMAY', 'DX': 'DISMAY', ':‑O': 'SURPRISE', ':O': 'SURPRISED', ':‑o': 'SURPRISE', ':o': 'SURPRISE', ':-0': 'SURPRISE', ':0': 'SURPRISE', '8‑0': 'SURPRISE', '>:O': 'SURPRISE', '=O': 'SURPRISE', '=o': 'SURPRISE', '=0': 'SURPRISE', ':-3': 'PLAYFUL_CUTE_CAT', ':3': 'PLAYFUL_CUTE_CAT', 'x3': 'PLAYFUL_CUTE_CAT', 'X3': 'PLAYFUL_CUTE_CAT', '>:3': 'EVIL', ':-*': 'KISS', ':*': 'KISS', ':x': 'KISS', ';‑)': 'WINK_SMIRK', ';)': 'WINK_SMIRK', '*-)': 'WINK_SMIRK', '*)': 'WINK_SMIRK', ';‑]': 'WINK_SMIRK', ';]': 'WINK_SMIRK', ';^)': 'WINK_SMIRK', ';>': 'WINK_SMIRK', ':‑,': 'WINK_SMIRK', ';D': 'WINK_SMIRK', ';3': 'WINK_SMIRK', ':‑P': 'PLAYFUL/CHEEKY_WITH_TONGUE', ':P': 'PLAYFUL/CHEEKY_WITH_TONGUE', 'X‑P': 'PLAYFUL/CHEEKY_WITH_TONGUE', 'XP': 'PLAYFUL/CHEEKY_WITH_TONGUE', 'x‑p': 'PLAYFUL/CHEEKY_WITH_TONGUE', 'xp': 'PLAYFUL/CHEEKY_WITH_TONGUE', ':‑p': 'PLAYFUL/CHEEKY_WITH_TONGUE', ':p': 'PLAYFUL/CHEEKY_WITH_TONGUE', ':‑Þ': 'PLAYFUL/CHEEKY_WITH_TONGUE', ':Þ': 'PLAYFUL/CHEEKY_WITH_TONGUE', ':‑þ': 'PLAYFUL/CHEEKY_WITH_TONGUE', ':þ': 'PLAYFUL/CHEEKY_WITH_TONGUE', ':‑b': 'PLAYFUL/CHEEKY_WITH_TONGUE', ':b': 'PLAYFUL/CHEEKY_WITH_TONGUE', 'd:': 'PLAYFUL/CHEEKY_WITH_TONGUE', '=p': 'PLAYFUL/CHEEKY_WITH_TONGUE', '>:b': 'PLAYFUL/CHEEKY_WITH_TONGUE', ':-/': 'SKEPTICAL_ANNOYED_UNEASY_HESITANT', ':/': 'SKEPTICAL_ANNOYED_UNEASY_HESITANT', "',:^I": 'SKEPTICAL_ANNOYED_UNEASY_HESITANT', '>:\\': 'SKEPTICAL_ANNOYED_UNEASY_HESITANT', '>:/': 'SKEPTICAL_ANNOYED_UNEASY_HESITANT', ':\\': 'SKEPTICAL_ANNOYED_UNEASY_HESITANT', '=/': 'SKEPTICAL_ANNOYED_UNEASY_HESITANT', '=\\': 'SKEPTICAL_ANNOYED_UNEASY_HESITANT', ':L': 'SKEPTICAL_ANNOYED_UNEASY_HESITANT', '=L': 'SKEPTICAL_ANNOYED_UNEASY_HESITANT', ':S': 'SKEPTICAL_ANNOYED_UNEASY_HESITANT', ':‑|': 'STRAIGHT_FACE_NO_EXPRESSION', ':|': 'STRAIGHT_FACE_NO_EXPRESSION', ':$': 'BLUSHING', '://)': 'BLUSHING', '://3': 'BLUSHING', ':‑X': 'SEALED-LIPS/TONGUE-TIED', ':X': 'SEALED-LIPS/TONGUE-TIED', ':‑#': 'SEALED-LIPS/TONGUE-TIED', ':#': 'SEALED-LIPS/TONGUE-TIED', ':‑&': 'SEALED-LIPS/TONGUE-TIED', ':&': 'SEALED-LIPS/TONGUE-TIED', 'O:‑)': 'ANGEL', 'O:)': 'ANGEL', '0:‑3': 'ANGEL', '0:3': 'ANGEL', '0:‑)': 'ANGEL', '0:)': 'ANGEL', '0;^)': 'ANGEL', '>:‑)': 'EVIL', '>:)': 'EVIL', '}:‑)': 'EVIL', '}:)': 'EVIL', '3:‑)': 'EVIL', '3:)': 'EVIL', '>;‑)': 'EVIL', '>;)': 'EVIL', '>;3': 'EVIL', '|;‑)': 'COOL', 'B-)': 'COOL', '|‑O': 'BORED_YAWNING', ':‑J': 'TONGUE-IN-CHEEK', '#‑)': 'PARTIED_ALL_NIGHT', '%‑)': 'DRUNK_CONFUSED', '%)': 'DRUNK_CONFUSED', ':‑###..': 'SICK', ':###..': 'SICK', '<:‑|': 'DUMB_DUNCE-LIKE', "',:-|": 'DISBELIEF', "',:-l": 'DISBELIEF', ':E': 'NERVOUS', '8-X': 'SKULL', '8=X': 'SKULL', 'x-3': 'SKULL', 'x=3': 'SKULL', '~:>': 'CHICKEN', '@};-': 'ROSE', '@}->--': 'ROSE', "@}‑;‑'‑‑‑": 'ROSE', '@>‑‑>‑‑': 'ROSE', '8====D': 'PENIS', '8===D': 'PENIS', '8=D': 'PENIS', '3=D': 'PENIS', '8=>': 'PENIS', '8===D~~~': 'PENIS', '*<|:‑)': 'SANTA', '</3': 'BROKEN_HEART', '<\\3': 'BROKEN_HEART', '<3': 'HEART', 's2': 'HEART', '><>': 'FISH', '<><': 'FISH', '<*)))‑{': 'FISH', '><(((*>': 'FISH', 'o/': 'HELLO/HIGH-FIVE', '\\o': 'HELLO/HIGH-FIVE', '\\o/': 'CHEER', '*\\0/*': 'CHEERLEADER', 'o7': 'SALUTE', 'v.v': 'DISMAY_WORDLESS', '._.': 'DISMAY_WORDLESS', '._.;': 'DISMAY_WORDLESS', ';-;': 'SAD_CRYING', 'T_T': 'CRYING', 'T-T': 'CRYING', 'QQ': 'SAD_CRYING', 'Qq': 'CRYING', 'qq': 'CRYING', 'X_X': 'DEAD', 'x_x': 'DEAD', '+_+': 'DEAD', 'X_x': 'DEAD', 'x_X': 'DEAD', '<_<': 'DEVIOUS/GUILTY', '>_>': 'DEVIOUS/GUILTY', '<.<': 'DEVIOUS/GUILTY', '>.>': 'DEVIOUS/GUILTY', 'O_O': 'SURPRISE', 'o_o': 'SURPRISE', 'O-O': 'SURPRISE', 'o‑o': 'SURPRISE', 'O_o': 'SURPRISE', 'o_O': 'SURPRISED', '>.<': 'UNDECIDED_HESITANT', '>_<': 'UNDECIDED_HESITANT', '^5': 'HIGH_FIVE', 'o/\\o': 'HIGH_FIVE', '>_>^ ^<_<': 'HIGH_FIVE', 'V.v.V': 'CRAB', 'V=(° °)=V': 'CRAB', '(^^^)': 'SHARK', '(::[]::)': 'BANDAGE', '(o)(o)': 'BREASTS', '( • )( • )': 'BREASTS', '(. Y .)': 'BREASTS', 'ӽd̲̅a̲̅r̲̅w̲̅i̲̅ɳ̲̅ᕗ': 'EVOLUTION_FISH', 'Ӽd̲̅a̲̅r̲̅w̲̅i̲̅ɳ̲̅ᕗ': 'EVOLUTION_FISH', 'ӽe̲̅v̲̅o̲̅l̲̅u̲̅t̲̅i̲̅o̲̅ɳ̲̅ᕗ': 'EVOLUTION_FISH', 'Ӽe̲̅v̲̅o̲̅l̲̅u̲̅t̲̅i̲̅o̲̅ɳ̲̅ᕗ': 'EVOLUTION_FISH', '[̲̅$̲̅(̲̅1̲̅)̲̅$̲̅]': 'DOLLAR', '[̲̅$̲̅(̲̅5̲̅)̲̅$̲̅]': 'DOLLAR', '[̲̅$̲̅(̲̅1̲̅0̲̅)̲̅$̲̅]': 'DOLLAR', '[̲̅$̲̅(̲̅ιοο̲̅)̲̅$̲̅]': 'DOLLAR', '(': 'AMAZED', '͡°': 'LENNY_FACE', '͜ʖ': 'LENNY_FACE', '͡°)': 'LENNY_FACE', 'ヽ༼ຈل͜ຈ༽ﾉ': 'RAISE_YOUR_DONGERS', 'ಠ_ಠ': 'DISAPPROVAL', 'ಠ__ಠ': 'DISAPPROVAL', 'ಠ益ಠ': 'DISAPPROVAL', '⎛⎝(•ⱅ•)⎠⎞': 'BAT', '◥▅◤': 'BAT', '◢▅◣': 'BAT', '(๑ˇεˇ๑)': 'KISS', '(◕‿◕✿)': 'FLOWER_GIRL', '( ༎ຶ \u06dd ༎ຶ )': 'CRYING', '(=ʘᆽʘ=)∫': 'CAT', 'ฅ(^•ﻌ•^ฅ)': 'CAT', 'ʕ •ᴥ•ʔ': 'BEAR', 'ʕ ·(エ)· ʔ': 'BEAR', 'ʕ – ㉨ – ʔ': 'BEAR', '⊂(￣(ｴ)￣)⊃': 'BEAR', '(>_<)': 'TROUBLED', '(>_<)>': 'TROUBLED', '(>w<)': 'TROUBLED', "(';')": 'BABY', '(^^ゞ': 'KISS', '(^_^;)': 'EMBARRASSED', '(-_-;)': 'EMBARRASSED', '(~_~;)': 'EMBARRASSED', '(・.・;)': 'EMBARRASSED', '(・_・;)': 'EMBARRASSED', '(・・;)': 'EMBARRASSED', '^^;': 'EMBARRASSED', '^_^;': 'EMBARRASSED', '(^^;)': 'EMBARRASSED', '(#^.^#)': 'NORMAL_LAUGH', '(⁄ ⁄•⁄ω⁄•⁄ ⁄)': 'FLUSHED', '(^.^)y-.o○': 'SMOKING', '(-.-)y-°°°': 'SMOKING', '(-_-)zzz': 'SLEEPING', '(^_-)': 'WINK', '(^_-)-☆': 'WINK', '((+_+))': 'CONFUSED', '(+o+)': 'CONFUSED', '(°°)': 'CONFUSED', '(°-°)': 'CONFUSED', '(°.°)': 'CONFUSED', '(°_°)': 'CONFUSED', '(°_°>)': 'CONFUSED', '(°レ°)': 'CONFUSED', '(o|o)': 'ULTRAMAN', '<(｀^´)>': 'HUMHUM', '^_^': 'NORMAL_LAUGH', '(°o°)': 'JOYFUL', '(^_^)/': 'JOYFUL', '(^O^)／': 'JOYFUL', '(^o^)／': 'JOYFUL', '(^^)/': 'JOYFUL', '(≧∇≦)/': 'CUTE_JOYFUL', '(/◕ヮ◕)/': 'CUTE_JOYFUL', '(^o^)丿': 'CUTE_JOYFUL', '∩(·ω·)∩': 'CUTE_JOYFUL', '(·ω·)': 'CUTE_JOYFUL', '^ω^': 'CUTE_JOYFUL', '(__)': 'RESPECT_APOLOGY', '_(._.)_': 'RESPECT_APOLOGY', '_(_^_)_': 'RESPECT_APOLOGY', '<(_ _)>': 'RESPECT_APOLOGY', '<m(__)m>': 'RESPECT_APOLOGY', 'm(__)m': 'RESPECT_APOLOGY', 'm(_ _)m': 'APOLOGY', '(凸ಠ益ಠ)凸': 'MIDDLE_FINGERS', '＼(°ロ＼)': 'QUESTIONING', '(／ロ°)／': 'QUESTIONING', "('_')": 'SAD_CRYING', '(/_;)': 'SAD_CRYING', '(T_T)': 'SAD_CRYING', '(;_;': 'SAD_CRYING', '(;_;)': 'SAD_CRYING', '(;_:)': 'SAD_CRYING', '(:_;)': 'SAD_CRYING', '(;O;)': 'SAD_CRYING', '(ToT)': 'SAD_CRYING', '(Ｔ▽Ｔ)': 'SAD_CRYING', ';_;': 'SAD_CRYING', ';n;': 'SAD_CRYING', ';;': 'SAD_CRYING', 'Q.Q': 'SAD_CRYING', 'T.T': 'SAD_CRYING', 'TnT': 'SAD_CRYING', 'Q_Q': 'SAD_CRYING', '(ー_ー)!!': 'SHAME', '(-.-)': 'SHAME', '(-_-)': 'SLEEPING', '(一一)': 'SHAME', '(；一_一)': 'SHAME', '(=_=)': 'TIRED', '(=^・^=)': 'CAT', '(=^・・^=)': 'CAT', '=^_^=': 'CAT', '(..)': 'LOOKING_DOWN', '(._.)': 'LOOKING_DOWN', '^m^': 'HUMHUM', '(・・?': 'CONFUSION', '(?_?)': 'CONFUSION', '(－‸ლ)': 'FACEPALM', '>^_^<': 'NORMAL_LAUGH', '<^!^>': 'NORMAL_LAUGH', '^/^（*^_^*）§^.^§': 'NORMAL_LAUGH', '(^<^)': 'NORMAL_LAUGH', '(^.^)': 'NORMAL_LAUGH', '(^ム^)': 'NORMAL_LAUGH', '(^·^)': 'NORMAL_LAUGH', '(^_^.)': 'NORMAL_LAUGH', '(^_^)': 'NORMAL_LAUGH', '(^^)': 'NORMAL_LAUGH', '(^J^)': 'NORMAL_LAUGH', '(*^.^*)': 'NORMAL_LAUGH', '（^—^）': 'NORMAL_LAUGH', '(^^)/~~~': 'WAVING', '(^_^)/~': 'WAVING', '(;_;)/~~~': 'WAVING', '(^.^)/~~~': 'WAVING', '(-_-)/~~~': 'WAVING', '($··)/~~~': 'WAVING', '(@^^)/~~~': 'WAVING', '(T_T)/~~~': 'WAVING', '(ToT)/~~~': 'WAVING', '＼(~o~)／': 'EXCITED', '＼(^o^)／': 'HOPELESS', '＼(-o-)／': 'EXCITED', 'ヽ(^。^)ノ': 'EXCITED', 'ヽ(^o^)丿': 'EXCITED', '(*^0^*)': 'EXCITED', '(*_*)': 'AMAZED', '(*_*;': 'AMAZED', '(+_+)': 'AMAZED', '(@_@)': 'AMAZED', '(@_@。(＠_＠;)': 'AMAZED', '＼(◎o◎)／！': 'AMAZED', '!(^^)!': 'HUMHUM!', '(*^^)v': 'LAUGHING_CHEERFUL', '(^^)v': 'LAUGHING_CHEERFUL', '(^_^)v（’-’*)': 'LAUGHING_CHEERFUL', '(＾ｖ＾)': 'HAPPY', '(＾▽＾)': 'LAUGHING_CHEERFUL', '(・∀・)': 'LAUGHING_CHEERFUL', '(´∀`)': 'LAUGHING_CHEERFUL', '(⌒▽⌒）': 'LAUGHING_CHEERFUL', '\\(^o^)/': 'HOPELESS', '(~o~)': 'EMMHUMHUM', '(~_~)': 'EMMHUMHUM', 'ˊ＿>ˋ': 'CALMNESS', '(p_-)': 'EMM', '(-_q)': 'EMM', '((d[-_-]b))': 'HEADPHONES', '(-"-)': 'WORRIED', '(ーー゛)': 'WORRIED', '(^_^メ)': 'WORRIED', '(-_-メ)': 'WORRIED', '(~_~メ)': 'WORRIED', '(－－〆)': 'WORRIED', '(・へ・)': 'WORRIED', '(｀´)': 'WORRIED', '<`～´>': 'WORRIED', '<`ヘ´>': 'WORRIED', '(ーー;)': 'WORRIED', '(^0_0^)': 'EYEGLASSES', '( ..)φ': 'JOTTING_NOTE', 'φ(..)': 'JOTTING_NOTE', '(●＾o＾●)': 'HAPPY', '(＾ｕ＾)': 'HAPPY', '(＾◇＾)': 'HAPPY', '( ^)o(^ )': 'HAPPY', '(^O^)': 'HAPPY', '(^o^)': 'HAPPY', '(^○^)': 'HAPPY', ')^o^(': 'HAPPY', '(*^▽^*)': 'HAPPY', '(✿◠‿◠)': 'HAPPY', '(￣ー￣)': 'SIMPER', '(￣□￣;)': 'SURPRISED', '°o°': 'SURPRISED', '°O°': 'SURPRISED', 'o_0': 'SURPRISED', 'o.O': 'SURPRISED', '(o.o)': 'SURPRISED', 'oO': 'SURPRISED', '(*´▽｀*)': 'INFATUATION', '(*°∀°)=3': 'INFATUATION', 'ᕕ( ᐛ )ᕗ': 'DANCING', '（': 'SURPRISED', 'ﾟ Дﾟ)': 'SHOCKED', '(°◇°)': 'SHOCKED', '(*￣m￣)': 'DISSATISFIED', 'ヽ(´ー｀)┌': 'SHRUG', '¯\\_(ツ)_/¯': 'SHRUG', '¯\\(°_o)/¯': 'SHRUG', '(´･ω･`)': 'HMM', '(‘A`)': 'SNUBBED/DEFLATED', '(づ￣': 'REACHING_AND_KISSING', '³￣)づ': 'REACHING_AND_KISSING', '(*^3^)/~☆': 'BLOWING_A_KISS', '.....φ(・∀・＊)': 'STUDYING', 'zzz(︶｡︶✽)': 'SLEEPING', 'uwu': 'CUTE_JOY', 'UwU': 'CUTE_JOY', 'OWO': 'WOW', 'OwO': 'WOW', '囧': 'DISTRESS', '.o○': 'BUBBLES', '○o.': 'BUBBLES', '( ^^)_U~~': 'CUP_OF_TEA', '( ^^)_旦~~': 'CUP_OF_TEA', '☆彡': 'SHOOTING_STAR', '☆ミ': 'SHOOTING_STAR', 'ᯓ✦': 'SHOOTING_STAR', '>°)))彡': 'FISH', '(Q  ))': 'FISH', '><ヨヨ': 'FISH', '(°))<<': 'FISH', '>°))))彡': 'FISH', '<°)))彡': 'FISH', '>°))彡': 'FISH', '<+': 'FISH', '))><<': 'FISH', '<*))': 'FISH', '>=<': 'FISH', '<コ:彡': 'SQUID', 'Ｃ:.ミ': 'SQUID', '~>°)～～～': 'SNAKE', '～°·_·°～': 'BAT', '(°°)～': 'TADPOLE', '●～*': 'BOMB', '￣|○': 'DESPAIR', 'STO': 'GIVEN_UP', 'OTZ': 'GIVEN_UP', 'OTL': 'GIVEN_UP', 'orz': 'DESPAIR', '囧rz': 'DESPAIR', '(╯°□°)╯︵ ┻━┻': 'TABLE_FLIP', '┬──┬ ¯\\_(ツ)': 'TABLE_FLIP', '┻━┻︵ヽ(`Д´)ﾉ︵': 'TABLE_FLIP', '┻━┻': 'TABLE_FLIP', '┬─┬ノ( º _ ºノ)': 'TABLE_FLIP', '(ノಠ益ಠ)ノ彡┻━┻': 'TABLE_FLIP', '|:3ミ': 'MEOW', '(`･ω･´)': 'FEEL_PERKY', '(｀-´)>': 'SALUTE', '(´；ω；`)': 'TERRIBLY_SAD', 'ヽ(´ー｀)ﾉ': 'WHATEVER', 'ヽ(`Д´)ﾉ': 'IRRITABLE', '(＃ﾟДﾟ)': 'ANGRY', '（ ´Д｀）': 'YELLING', 'ﾟДﾟ）': 'SURPRISED', "┐('～`；)┌": 'NO_IDEA_SHRUG', '（´∀｀）': 'CAREFREE', '（ ´_ゝ`）': 'INDIFFERENT', 'Σ(゜д゜;)': 'SHOCKED', 'ﾟヮﾟ)': 'UPBEAT', '⊂二二二（＾ω＾）二⊃': 'BU-N!', '(((( ；ﾟДﾟ)))': 'SPOOK', 'Σ(ﾟДﾟ)': 'HUGE_SURPRISE', '( ´∀｀)σ)∀`)': 'POKE_CHEEK', 'ﾟдﾟ)': 'AMAZED', '(´ー`)y-~~': 'SMOKING', '（ ^_^）o自自o（^_^ ）': 'CHEERS', 'm9(・∀・)': 'FLASH_OF_INTUITION', 'ヽ(´ー`)人(´∇｀)人(`Д´)ノ': 'FRIENDLY', "('A`)": 'LONELY', '（ ´,_ゝ`)': 'DEPRESSED', '（´-`）.｡oO( ...nbsp;)': 'THINKING', '(ﾟДﾟ;≡;ﾟДﾟ)': 'ANXIETY', '( ´д)ﾋｿ(´Д｀)ﾋｿ(Д｀)': 'WHISPERS', '（･∀･)つ⑩': 'CARRYING_MONEY', '⊂（ﾟДﾟ⊂⌒｀つ': 'SLIDING', '≡≡≡(´⌒;;;≡≡≡': 'SLIDING', '(ﾟдﾟ)': 'UNFORESEEN', '(ﾟ⊿ﾟ)': "I_DON'T_NEED_IT", 'щ(ﾟДﾟщ)': 'COME_ON', '(屮ﾟДﾟ)屮': 'COME_ON', '（・∀・）': 'MOCKING', '（・Ａ・）': "THAT'S_BAD", '(ﾟ∀ﾟ)': 'DRUG-IN-BRAIN', '（つ Д ｀）': 'SAD', 'エェェ(´д｀)ェェエ': 'NOT_CONVINCING', '♪┏(・o･)┛♪┗ ( ･o･) ┓': 'DANCING_TO_THE_MUSIC', 'd(*⌒▽⌒*)b': 'HAPPY', '＿￣': 'GIVEN_UP', '(╬': 'EXTREME_DISTASTE', 'ಠ益ಠ)': 'EXTREME_DISTASTE', '(≧ロ≦)': 'SHOUTING', '(ΘεΘ;)': 'AWKWARD', '＼ ￣ヘ￣': 'KICK', '┌(；`～,)┐': 'DISCOMBOBULATED', 'ε=ε=ε=┌(;*´Д`)ﾉ': 'RUNNING', 'ヽ(´▽`)/': 'HAPPY', '^ㅂ^': 'HAPPY', "(l'o'l)": 'SHOCKED', 'ヽ(o`皿′o)ﾉ': 'REALLY_ANGRY', '(☞ﾟヮﾟ)☞': 'DO_IT', '☜(ﾟヮﾟ☜)': 'DO_IT', '☜(⌒▽⌒)☞': 'ANGEL', 'キタ━━━(゜∀゜)━━━!!!!!': "IT'S_HERE_I_CAME", 'ｷﾀﾜァ*･゜ﾟ･*:.｡..｡.:*･゜': "IT'S_HERE_I_CAME", '(n‘∀‘)ηﾟ･*:.｡. .｡.:*･゜ﾟ･*!!!!!': "IT'S_HERE_I_CAME", '(*´Д`)ﾊｧﾊｧ': 'EROTIC', '( ´Д｀)ﾉ(´･ω･`)': 'PATTING', 'ﾅﾃﾞﾅﾃﾞ': 'PATTING', '(*ﾟﾉOﾟ)<ｵｵｵｵｫｫｫｫｫｫｫｰｰｰｰｰｲ!': 'CALLING_OUT', '（・∀・ ）': 'BLAMING', 'ヾ(- - )コラコラ': 'BLAMING', 'お(^o^)や(^O^)す(^｡^)みぃ(^-^)ﾉﾞ': 'GOOD_NIGHT'}

In [14]:
def preprocess(row):
    entity = row["entity"]
    text = row["text"]

    FLAG = re.I

    emoji_pattern = r"(\ud83c[d000-dfff]|\ud83d[d000-dfff]|\ud83e[d000-dfff])"

    url_pattern = r'(https?:\/\/)?(([\w\-]{1,63}\.)+[\w\-]{1,63})(\/[\w.\-]+)*([?=+%\w~\-.&]*)'
    entity_pattern = rf"@?{entity}"
    user_pattern = r"@\w+"
    repeated_pattern = r"(.)\1\1\1+"
    repeated_replace_pattern = r"\1\1\1"
    
    # Concate if potential URL/Username
    text = re.sub(r"\s+\/(\s+)?", "/", text)
    text = re.sub(r"\@\s+", "@", text)

    # Replaces URL
    text = re.sub(url_pattern, '<URL>', text)

    # Replaces entity and other_user
    text = re.sub(entity_pattern, "<ENTITY>", text, flags=FLAG)
    text = re.sub(user_pattern, "<OTHER_USER>", text)

    # Raplaces repeated patterns
    text = re.sub(repeated_pattern, repeated_replace_pattern, text)
    
    tokens = tokenizer.tokenize(text)

    for i, token in enumerate(tokens):
        # Replaces emoji
        if emoji.is_emoji(token):
            print(f"{row.name}: {token}")
            meaning = emoji.demojize(token)[1:-1]
            emoji_replacement = f"<EMOJI_{meaning.upper()}>"
            print(f"{token} -> {emoji_replacement}")
            tokens[i] = emoji_replacement
        elif token in emoticon_dict and len(token) > 1:
            print(f"==Row {row.name}== {token}")
            meaning = emoticon_dict[token]
            emoticon_replacement = f"<EMOTICON_{meaning}>"
            print(f"{token} -> {emoticon_replacement}")
            tokens[i] = emoticon_replacement
        else:
            continue
    
    return tokens

In [15]:
df["cleaned_text"] = df.apply(preprocess, axis=1)

==Row 6== :)
:) -> <EMOTICON_SMILEY>
==Row 7== :)
:) -> <EMOTICON_SMILEY>
==Row 9== :)
:) -> <EMOTICON_SMILEY>
==Row 10== :)
:) -> <EMOTICON_SMILEY>
78: ‼
‼ -> <EMOJI_DOUBLE_EXCLAMATION_MARK>
81: ‼
‼ -> <EMOJI_DOUBLE_EXCLAMATION_MARK>
==Row 120== :)
:) -> <EMOTICON_SMILEY>
==Row 121== :)
:) -> <EMOTICON_SMILEY>
==Row 122== :)
:) -> <EMOTICON_SMILEY>
==Row 123== :)
:) -> <EMOTICON_SMILEY>
==Row 125== :)
:) -> <EMOTICON_SMILEY>
222: 1⃣
1⃣ -> <EMOJI_KEYCAP_1>
225: 1⃣
1⃣ -> <EMOJI_KEYCAP_1>
==Row 289== :/
:/ -> <EMOTICON_SKEPTICAL_ANNOYED_UNEASY_HESITANT>
==Row 385== :/
:/ -> <EMOTICON_SKEPTICAL_ANNOYED_UNEASY_HESITANT>
==Row 535== :/
:/ -> <EMOTICON_SKEPTICAL_ANNOYED_UNEASY_HESITANT>
==Row 536== :/
:/ -> <EMOTICON_SKEPTICAL_ANNOYED_UNEASY_HESITANT>
576: 🤔
🤔 -> <EMOJI_THINKING_FACE>
579: 🤔
🤔 -> <EMOJI_THINKING_FACE>
==Row 582== </3
</3 -> <EMOTICON_BROKEN_HEART>
==Row 583== </3
</3 -> <EMOTICON_BROKEN_HEART>
==Row 585== </3
</3 -> <EMOTICON_BROKEN_HEART>
==Row 586== </3
</3 -> <EMOTICON_BROKEN_HEART>
==Row 587== </3
</3 -> <EMOTICON_BROKEN_HEART>
648: 🤔
🤔 -> <EMOJI_THINKING_FACE>
651: 🤔
🤔 -> <EMOJI_THINKING_FACE>
652: 🤔
🤔 -> <EMOJI_THINKING_FACE>
672: 🥰
🥰 -> <EMOJI_SMILING_FACE_WITH_HEARTS>
672: 🥰
🥰 -> <EMOJI_SMILING_FACE_WITH_HEARTS>
672: 🥰
🥰 -> <EMOJI_SMILING_FACE_WITH_HEARTS>
==Row 675== :)
:) -> <EMOTICON_SMILEY>
==Row 678== :)
:) -> <EMOTICON_SMILEY>
==Row 678== :D
:D -> <EMOTICON_BIG_GRIN>
==Row 679== :)
:) -> <EMOTICON_SMILEY>
==Row 680== :)
:) -> <EMOTICON_SMILEY>
==Row 681== :)
:) -> <EMOTICON_SMILEY>
==Row 681== :D
:D -> <EMOTICON_BIG_GRIN>
==Row 683== :)
:) -> <EMOTICON_SMILEY>
==Row 683== :D
:D -> <EMOTICON_BIG_GRIN>
708: 🤞
🤞 -> <EMOJI_CROSSED_FINGERS>
711: 🤞
🤞 -> <EMOJI_CROSSED_FINGERS>
==Row 721== :/
:/ -> <EMOTICON_SKEPTICAL_ANNOYED_UNEASY_HESITANT>
==Row 823== :/
:/ -> <EMOTICON_SKEPTICAL_ANNOYED_UNEASY_HESITANT>
894: 🧨
🧨 -> <EMOJI_FIRECRACKER>
894: 🧨
🧨 -> <EMOJI_FIRECRACKER>
897: 🧨
🧨 -> <EMOJI_FIRECRACKER>
897: 🧨
🧨 -> <EMOJI_FIRECRACKER>
==Row 900== :(
:( -> <EMOTICON_FROWN_SAD>
==Row 903== :(
:( -> <EMOTICON_FROWN_SAD>
==Row 905== :(
:( -> <EMOTICON_FROWN_SAD>
1074: 🧘
🧘 -> <EMOJI_PERSON_IN_LOTUS_POSITION>
1074: 🧘
🧘 -> <EMOJI_PERSON_IN_LOTUS_POSITION>
1077: 🧘
🧘 -> <EMOJI_PERSON_IN_LOTUS_POSITION>
1077: 🧘
🧘 -> <EMOJI_PERSON_IN_LOTUS_POSITION>
1078: 🧘
🧘 -> <EMOJI_PERSON_IN_LOTUS_POSITION>
1078: 🧘
🧘 -> <EMOJI_PERSON_IN_LOTUS_POSITION>
1128: 🤔
🤔 -> <EMOJI_THINKING_FACE>
1131: 🤔
🤔 -> <EMOJI_THINKING_FACE>
1272: 🤯
🤯 -> <EMOJI_EXPLODING_HEAD>
1275: 🤯
🤯 -> <EMOJI_EXPLODING_HEAD>
==Row 1327== :/
:/ -> <EMOTICON_SKEPTICAL_ANNOYED_UNEASY_HESITANT>
==Row 1328== :/
:/ -> <EMOTICON_SKEPTICAL_ANNOYED_UNEASY_HESITANT>
==Row 1429== :/
:/ -> <EMOTICON_SKEPTICAL_ANNOYED_UNEASY_HESITANT>
==Row 1596== :/
:/ -> <EMOTICON_SKEPTICAL_ANNOYED_UNEASY_HESITANT>
==Row 1597== :/
:/ -> <EMOTICON_SKEPTICAL_ANNOYED_UNEASY_HESITANT>
==Row 1598== :/
:/ -> <EMOTICON_SKEPTICAL_ANNOYED_UNEASY_HESITANT>
==Row 1599== :/
:/ -> <EMOTICON_SKEPTICAL_ANNOYED_UNEASY_HESITANT>
==Row 1600== :/
:/ -> <EMOTICON_SKEPTICAL_ANNOYED_UNEASY_HESITANT>
==Row 1601== :/
:/ -> <EMOTICON_SKEPTICAL_ANNOYED_UNEASY_HESITANT>
==Row 1615== :/
:/ -> <EMOTICON_SKEPTICAL_ANNOYED_UNEASY_HESITANT>
==Row 1616== :/
:/ -> <EMOTICON_SKEPTICAL_ANNOYED_UNEASY_HESITANT>
==Row 1716== :D
:D -> <EMOTICON_BIG_GRIN>
==Row 1719== :D
:D -> <EMOTICON_BIG_GRIN>
==Row 1720== :D
:D -> <EMOTICON_BIG_GRIN>
==Row 1747== :/
:/ -> <EMOTICON_SKEPTICAL_ANNOYED_UNEASY_HESITANT>
==Row 1748== :/
:/ -> <EMOTICON_SKEPTICAL_ANNOYED_UNEASY_HESITANT>
==Row 1790== D;
D; -> <EMOTICON_SADNESS>
==Row 1825== :/
:/ -> <EMOTICON_SKEPTICAL_ANNOYED_UNEASY_HESITANT>
==Row 1986== uwu
uwu -> <EMOTICON_CUTE_JOY>
==Row 1987== uwu
uwu -> <EMOTICON_CUTE_JOY>
==Row 1990== uwu
uwu -> <EMOTICON_CUTE_JOY>
==Row 1991== uwu
uwu -> <EMOTICON_CUTE_JOY>
==Row 2061== :)
:) -> <EMOTICON_SMILEY>
==Row 2106== :D
:D -> <EMOTICON_BIG_GRIN>
==Row 2111== :D
:D -> <EMOTICON_BIG_GRIN>
2232: 🤞
🤞 -> <EMOJI_CROSSED_FINGERS>
2235: 🤞
🤞 -> <EMOJI_CROSSED_FINGERS>
==Row 2251== :/
:/ -> <EMOTICON_SKEPTICAL_ANNOYED_UNEASY_HESITANT>
==Row 2252== :/
:/ -> <EMOTICON_SKEPTICAL_ANNOYED_UNEASY_HESITANT>
==Row 2401== :/
:/ -> <EMOTICON_SKEPTICAL_ANNOYED_UNEASY_HESITANT>
==Row 2402== :/
:/ -> <EMOTICON_SKEPTICAL_ANNOYED_UNEASY_HESITANT>
==Row 2437== :/
:/ -> <EMOTICON_SKEPTICAL_ANNOYED_UNEASY_HESITANT>
==Row 2438== :/
:/ -> <EMOTICON_SKEPTICAL_ANNOYED_UNEASY_HESITANT>
==Row 2461== :/
:/ -> <EMOTICON_SKEPTICAL_ANNOYED_UNEASY_HESITANT>
2484: 🤦
🤦 -> <EMOJI_PERSON_FACEPALMING>
2487: 🤦
🤦 -> <EMOJI_PERSON_FACEPALMING>
==Row 2515== :/
:/ -> <EMOTICON_SKEPTICAL_ANNOYED_UNEASY_HESITANT>
==Row 2516== :/
:/ -> <EMOTICON_SKEPTICAL_ANNOYED_UNEASY_HESITANT>
==Row 2695== :/
:/ -> <EMOTICON_SKEPTICAL_ANNOYED_UNEASY_HESITANT>
==Row 3067== :/
:/ -> <EMOTICON_SKEPTICAL_ANNOYED_UNEASY_HESITANT>
==Row 3231== :)
:) -> <EMOTICON_SMILEY>
==Row 3327== :)
:) -> <EMOTICON_SMILEY>
==Row 3349== :/
:/ -> <EMOTICON_SKEPTICAL_ANNOYED_UNEASY_HESITANT>
==Row 3350== :/
:/ -> <EMOTICON_SKEPTICAL_ANNOYED_UNEASY_HESITANT>
3450: 🤣
🤣 -> <EMOJI_ROLLING_ON_THE_FLOOR_LAUGHING>
3450: 🤦
🤦 -> <EMOJI_PERSON_FACEPALMING>
3453: 🤣
🤣 -> <EMOJI_ROLLING_ON_THE_FLOOR_LAUGHING>
3546: 🤩
🤩 -> <EMOJI_STAR-STRUCK>
3546: ‼
‼ -> <EMOJI_DOUBLE_EXCLAMATION_MARK>
3564: 🥺
🥺 -> <EMOJI_PLEADING_FACE>
3567: 🥺
🥺 -> <EMOJI_PLEADING_FACE>
==Row 3595== :/
:/ -> <EMOTICON_SKEPTICAL_ANNOYED_UNEASY_HESITANT>
==Row 3596== :/
:/ -> <EMOTICON_SKEPTICAL_ANNOYED_UNEASY_HESITANT>
3606: 🥺
🥺 -> <EMOJI_PLEADING_FACE>
3609: 🥺
🥺 -> <EMOJI_PLEADING_FACE>
3624: 🤔
🤔 -> <EMOJI_THINKING_FACE>
==Row 3715== :/
:/ -> <EMOTICON_SKEPTICAL_ANNOYED_UNEASY_HESITANT>
==Row 3716== :/
:/ -> <EMOTICON_SKEPTICAL_ANNOYED_UNEASY_HESITANT>
==Row 3781== :/
:/ -> <EMOTICON_SKEPTICAL_ANNOYED_UNEASY_HESITANT>
==Row 3782== :/
:/ -> <EMOTICON_SKEPTICAL_ANNOYED_UNEASY_HESITANT>
3888: 🥴
🥴 -> <EMOJI_WOOZY_FACE>
3891: 🥴
🥴 -> <EMOJI_WOOZY_FACE>
3942: 🤞
🤞 -> <EMOJI_CROSSED_FINGERS>
3945: 🤞
🤞 -> <EMOJI_CROSSED_FINGERS>
3946: 🤞
🤞 -> <EMOJI_CROSSED_FINGERS>
3948: 🥰
🥰 -> <EMOJI_SMILING_FACE_WITH_HEARTS>
3951: 🥰
🥰 -> <EMOJI_SMILING_FACE_WITH_HEARTS>
3952: 🥰
🥰 -> <EMOJI_SMILING_FACE_WITH_HEARTS>
==Row 3955== :/
:/ -> <EMOTICON_SKEPTICAL_ANNOYED_UNEASY_HESITANT>
==Row 3956== :/
:/ -> <EMOTICON_SKEPTICAL_ANNOYED_UNEASY_HESITANT>
==Row 4020== :/
:/ -> <EMOTICON_SKEPTICAL_ANNOYED_UNEASY_HESITANT>
==Row 4021== :/
:/ -> <EMOTICON_SKEPTICAL_ANNOYED_UNEASY_HESITANT>
==Row 4022== :/
:/ -> <EMOTICON_SKEPTICAL_ANNOYED_UNEASY_HESITANT>
==Row 4024== :/
:/ -> <EMOTICON_SKEPTICAL_ANNOYED_UNEASY_HESITANT>
==Row 4025== :/
:/ -> <EMOTICON_SKEPTICAL_ANNOYED_UNEASY_HESITANT>
4056: 🤢
🤢 -> <EMOJI_NAUSEATED_FACE>
4059: 🤢
🤢 -> <EMOJI_NAUSEATED_FACE>
4116: 🤩
🤩 -> <EMOJI_STAR-STRUCK>
4116: 🤩
🤩 -> <EMOJI_STAR-STRUCK>
4119: 🤩
🤩 -> <EMOJI_STAR-STRUCK>
4119: 🤩
🤩 -> <EMOJI_STAR-STRUCK>
==Row 4530== :)
:) -> <EMOTICON_SMILEY>
==Row 4531== :)
:) -> <EMOTICON_SMILEY>
==Row 4532== :)
:) -> <EMOTICON_SMILEY>
==Row 4533== :)
:) -> <EMOTICON_SMILEY>
==Row 4535== :)
:) -> <EMOTICON_SMILEY>
==Row 4687== :/
:/ -> <EMOTICON_SKEPTICAL_ANNOYED_UNEASY_HESITANT>
==Row 4688== :/
:/ -> <EMOTICON_SKEPTICAL_ANNOYED_UNEASY_HESITANT>
==Row 4699== :/
:/ -> <EMOTICON_SKEPTICAL_ANNOYED_UNEASY_HESITANT>
==Row 4700== :/
:/ -> <EMOTICON_SKEPTICAL_ANNOYED_UNEASY_HESITANT>
==Row 4717== :/
:/ -> <EMOTICON_SKEPTICAL_ANNOYED_UNEASY_HESITANT>
==Row 4718== :/
:/ -> <EMOTICON_SKEPTICAL_ANNOYED_UNEASY_HESITANT>
4800: 🥳
🥳 -> <EMOJI_PARTYING_FACE>
4803: 🥳
🥳 -> <EMOJI_PARTYING_FACE>
==Row 4849== :/
:/ -> <EMOTICON_SKEPTICAL_ANNOYED_UNEASY_HESITANT>
==Row 4885== :/
:/ -> <EMOTICON_SKEPTICAL_ANNOYED_UNEASY_HESITANT>
==Row 4933== :/
:/ -> <EMOTICON_SKEPTICAL_ANNOYED_UNEASY_HESITANT>
==Row 4941== :)
:) -> <EMOTICON_SMILEY>
==Row 4945== :/
:/ -> <EMOTICON_SKEPTICAL_ANNOYED_UNEASY_HESITANT>
==Row 4946== :/
:/ -> <EMOTICON_SKEPTICAL_ANNOYED_UNEASY_HESITANT>
==Row 4999== :/
:/ -> <EMOTICON_SKEPTICAL_ANNOYED_UNEASY_HESITANT>
==Row 5011== :/
:/ -> <EMOTICON_SKEPTICAL_ANNOYED_UNEASY_HESITANT>
==Row 5041== :/
:/ -> <EMOTICON_SKEPTICAL_ANNOYED_UNEASY_HESITANT>
==Row 5047== :/
:/ -> <EMOTICON_SKEPTICAL_ANNOYED_UNEASY_HESITANT>
==Row 5065== :/
:/ -> <EMOTICON_SKEPTICAL_ANNOYED_UNEASY_HESITANT>
==Row 5066== :/
:/ -> <EMOTICON_SKEPTICAL_ANNOYED_UNEASY_HESITANT>
==Row 5083== :/
:/ -> <EMOTICON_SKEPTICAL_ANNOYED_UNEASY_HESITANT>
==Row 5084== :/
:/ -> <EMOTICON_SKEPTICAL_ANNOYED_UNEASY_HESITANT>
==Row 5131== :/
:/ -> <EMOTICON_SKEPTICAL_ANNOYED_UNEASY_HESITANT>
==Row 5155== :/
:/ -> <EMOTICON_SKEPTICAL_ANNOYED_UNEASY_HESITANT>
5160: 🤦
🤦 -> <EMOJI_PERSON_FACEPALMING>
5163: 🤦
🤦 -> <EMOJI_PERSON_FACEPALMING>
==Row 5167== :/
:/ -> <EMOTICON_SKEPTICAL_ANNOYED_UNEASY_HESITANT>
==Row 5173== :/
:/ -> <EMOTICON_SKEPTICAL_ANNOYED_UNEASY_HESITANT>
==Row 5257== :/
:/ -> <EMOTICON_SKEPTICAL_ANNOYED_UNEASY_HESITANT>
==Row 5275== :/
:/ -> <EMOTICON_SKEPTICAL_ANNOYED_UNEASY_HESITANT>
5280: 🤔
🤔 -> <EMOJI_THINKING_FACE>
5283: 🤔
🤔 -> <EMOJI_THINKING_FACE>
==Row 5287== :/
:/ -> <EMOTICON_SKEPTICAL_ANNOYED_UNEASY_HESITANT>
==Row 5306== ;)
;) -> <EMOTICON_WINK_SMIRK>
==Row 5306== ;)
;) -> <EMOTICON_WINK_SMIRK>
==Row 5306== ;)
;) -> <EMOTICON_WINK_SMIRK>
==Row 5306== ;)
;) -> <EMOTICON_WINK_SMIRK>
==Row 5306== ;)
;) -> <EMOTICON_WINK_SMIRK>
==Row 5306== ;)
;) -> <EMOTICON_WINK_SMIRK>
==Row 5306== ;)
;) -> <EMOTICON_WINK_SMIRK>
==Row 5306== ;)
;) -> <EMOTICON_WINK_SMIRK>
==Row 5306== ;)
;) -> <EMOTICON_WINK_SMIRK>
==Row 5306== ;)
;) -> <EMOTICON_WINK_SMIRK>
==Row 5306== ;)
;) -> <EMOTICON_WINK_SMIRK>
==Row 5306== ;)
;) -> <EMOTICON_WINK_SMIRK>
==Row 5306== ;)
;) -> <EMOTICON_WINK_SMIRK>
==Row 5306== ;)
;) -> <EMOTICON_WINK_SMIRK>
==Row 5306== ;)
;) -> <EMOTICON_WINK_SMIRK>
==Row 5306== ;)
;) -> <EMOTICON_WINK_SMIRK>
==Row 5306== ;)
;) -> <EMOTICON_WINK_SMIRK>
==Row 5306== ;)
;) -> <EMOTICON_WINK_SMIRK>
==Row 5306== ;)
;) -> <EMOTICON_WINK_SMIRK>
==Row 5306== ;)
;) -> <EMOTICON_WINK_SMIRK>
==Row 5306== ;)
;) -> <EMOTICON_WINK_SMIRK>
==Row 5306== ;)
;) -> <EMOTICON_WINK_SMIRK>
==Row 5306== ;)
;) -> <EMOTICON_WINK_SMIRK>
==Row 5306== ;)
;) -> <EMOTICON_WINK_SMIRK>
==Row 5306== ;)
;) -> <EMOTICON_WINK_SMIRK>
==Row 5306== ;)
;) -> <EMOTICON_WINK_SMIRK>
==Row 5306== ;)
;) -> <EMOTICON_WINK_SMIRK>
==Row 5306== ;)
;) -> <EMOTICON_WINK_SMIRK>
==Row 5306== ;)
;) -> <EMOTICON_WINK_SMIRK>
==Row 5306== ;)
;) -> <EMOTICON_WINK_SMIRK>
==Row 5306== ;)
;) -> <EMOTICON_WINK_SMIRK>
==Row 5306== ;)
;) -> <EMOTICON_WINK_SMIRK>
==Row 5306== ;)
;) -> <EMOTICON_WINK_SMIRK>
==Row 5306== ;)
;) -> <EMOTICON_WINK_SMIRK>
==Row 5306== ;)
;) -> <EMOTICON_WINK_SMIRK>
==Row 5306== ;)
;) -> <EMOTICON_WINK_SMIRK>
==Row 5306== ;)
;) -> <EMOTICON_WINK_SMIRK>
==Row 5306== ;)
;) -> <EMOTICON_WINK_SMIRK>
==Row 5306== ;)
;) -> <EMOTICON_WINK_SMIRK>
==Row 5306== ;)
;) -> <EMOTICON_WINK_SMIRK>
==Row 5306== ;)
;) -> <EMOTICON_WINK_SMIRK>
==Row 5306== ;)
;) -> <EMOTICON_WINK_SMIRK>
==Row 5306== ;)
;) -> <EMOTICON_WINK_SMIRK>
==Row 5306== ;)
;) -> <EMOTICON_WINK_SMIRK>
==Row 5306== ;)
;) -> <EMOTICON_WINK_SMIRK>
==Row 5306== ;)
;) -> <EMOTICON_WINK_SMIRK>
==Row 5306== ;)
;) -> <EMOTICON_WINK_SMIRK>
==Row 5306== ;)
;) -> <EMOTICON_WINK_SMIRK>
==Row 5306== ;)
;) -> <EMOTICON_WINK_SMIRK>
==Row 5306== ;)
;) -> <EMOTICON_WINK_SMIRK>
==Row 5306== ;)
;) -> <EMOTICON_WINK_SMIRK>
==Row 5306== ;)
;) -> <EMOTICON_WINK_SMIRK>
==Row 5306== ;)
;) -> <EMOTICON_WINK_SMIRK>
==Row 5306== ;)
;) -> <EMOTICON_WINK_SMIRK>
==Row 5306== ;)
;) -> <EMOTICON_WINK_SMIRK>
==Row 5306== ;)
;) -> <EMOTICON_WINK_SMIRK>
==Row 5306== ;)
;) -> <EMOTICON_WINK_SMIRK>
==Row 5306== ;)
;) -> <EMOTICON_WINK_SMIRK>
==Row 5306== ;)
;) -> <EMOTICON_WINK_SMIRK>
==Row 5306== ;)
;) -> <EMOTICON_WINK_SMIRK>
==Row 5306== ;)
;) -> <EMOTICON_WINK_SMIRK>
==Row 5306== ;)
;) -> <EMOTICON_WINK_SMIRK>
==Row 5306== ;)
;) -> <EMOTICON_WINK_SMIRK>
==Row 5341== :/
:/ -> <EMOTICON_SKEPTICAL_ANNOYED_UNEASY_HESITANT>
5430: 🤟
🤟 -> <EMOJI_LOVE-YOU_GESTURE>
5430: 🤳
🤳 -> <EMOJI_SELFIE>
5430: 🤷
🤷 -> <EMOJI_PERSON_SHRUGGING>
5433: 🤟
🤟 -> <EMOJI_LOVE-YOU_GESTURE>
5433: 🤳
🤳 -> <EMOJI_SELFIE>
5433: 🤷
🤷 -> <EMOJI_PERSON_SHRUGGING>
5434: 🤟
🤟 -> <EMOJI_LOVE-YOU_GESTURE>
5434: 🤳
🤳 -> <EMOJI_SELFIE>
5434: 🤷
🤷 -> <EMOJI_PERSON_SHRUGGING>
==Row 5437== :/
:/ -> <EMOTICON_SKEPTICAL_ANNOYED_UNEASY_HESITANT>
==Row 5461== :/
:/ -> <EMOTICON_SKEPTICAL_ANNOYED_UNEASY_HESITANT>
==Row 5527== :/
:/ -> <EMOTICON_SKEPTICAL_ANNOYED_UNEASY_HESITANT>
5562: 🤣
🤣 -> <EMOJI_ROLLING_ON_THE_FLOOR_LAUGHING>
==Row 5599== :/
:/ -> <EMOTICON_SKEPTICAL_ANNOYED_UNEASY_HESITANT>
==Row 5635== :/
:/ -> <EMOTICON_SKEPTICAL_ANNOYED_UNEASY_HESITANT>
==Row 5636== :/
:/ -> <EMOTICON_SKEPTICAL_ANNOYED_UNEASY_HESITANT>
==Row 5659== :/
:/ -> <EMOTICON_SKEPTICAL_ANNOYED_UNEASY_HESITANT>
==Row 5660== :/
:/ -> <EMOTICON_SKEPTICAL_ANNOYED_UNEASY_HESITANT>
==Row 5695== :/
:/ -> <EMOTICON_SKEPTICAL_ANNOYED_UNEASY_HESITANT>
==Row 5707== :/
:/ -> <EMOTICON_SKEPTICAL_ANNOYED_UNEASY_HESITANT>
==Row 5713== :/
:/ -> <EMOTICON_SKEPTICAL_ANNOYED_UNEASY_HESITANT>
==Row 5714== :/
:/ -> <EMOTICON_SKEPTICAL_ANNOYED_UNEASY_HESITANT>
==Row 5743== :/
:/ -> <EMOTICON_SKEPTICAL_ANNOYED_UNEASY_HESITANT>
==Row 5744== :/
:/ -> <EMOTICON_SKEPTICAL_ANNOYED_UNEASY_HESITANT>
==Row 5761== :/
:/ -> <EMOTICON_SKEPTICAL_ANNOYED_UNEASY_HESITANT>
==Row 5833== :/
:/ -> <EMOTICON_SKEPTICAL_ANNOYED_UNEASY_HESITANT>
==Row 5834== :/
:/ -> <EMOTICON_SKEPTICAL_ANNOYED_UNEASY_HESITANT>
==Row 5947== :/
:/ -> <EMOTICON_SKEPTICAL_ANNOYED_UNEASY_HESITANT>
==Row 6049== :/
:/ -> <EMOTICON_SKEPTICAL_ANNOYED_UNEASY_HESITANT>
==Row 6050== :/
:/ -> <EMOTICON_SKEPTICAL_ANNOYED_UNEASY_HESITANT>
==Row 6055== :/
:/ -> <EMOTICON_SKEPTICAL_ANNOYED_UNEASY_HESITANT>
==Row 6056== :/
:/ -> <EMOTICON_SKEPTICAL_ANNOYED_UNEASY_HESITANT>
==Row 6073== :/
:/ -> <EMOTICON_SKEPTICAL_ANNOYED_UNEASY_HESITANT>
==Row 6074== :/
:/ -> <EMOTICON_SKEPTICAL_ANNOYED_UNEASY_HESITANT>
==Row 6109== :/
:/ -> <EMOTICON_SKEPTICAL_ANNOYED_UNEASY_HESITANT>
==Row 6110== :/
:/ -> <EMOTICON_SKEPTICAL_ANNOYED_UNEASY_HESITANT>
6132: 🥺
🥺 -> <EMOJI_PLEADING_FACE>
6135: 🥺
🥺 -> <EMOJI_PLEADING_FACE>
==Row 6157== :/
:/ -> <EMOTICON_SKEPTICAL_ANNOYED_UNEASY_HESITANT>
==Row 6181== :/
:/ -> <EMOTICON_SKEPTICAL_ANNOYED_UNEASY_HESITANT>
==Row 6187== :/
:/ -> <EMOTICON_SKEPTICAL_ANNOYED_UNEASY_HESITANT>
==Row 6188== :/
:/ -> <EMOTICON_SKEPTICAL_ANNOYED_UNEASY_HESITANT>
==Row 6271== :/
:/ -> <EMOTICON_SKEPTICAL_ANNOYED_UNEASY_HESITANT>
==Row 6272== :/
:/ -> <EMOTICON_SKEPTICAL_ANNOYED_UNEASY_HESITANT>
==Row 6283== :/
:/ -> <EMOTICON_SKEPTICAL_ANNOYED_UNEASY_HESITANT>
==Row 6284== :/
:/ -> <EMOTICON_SKEPTICAL_ANNOYED_UNEASY_HESITANT>
==Row 6313== :/
:/ -> <EMOTICON_SKEPTICAL_ANNOYED_UNEASY_HESITANT>
==Row 6314== :/
:/ -> <EMOTICON_SKEPTICAL_ANNOYED_UNEASY_HESITANT>
==Row 6319== :/
:/ -> <EMOTICON_SKEPTICAL_ANNOYED_UNEASY_HESITANT>
==Row 6320== :/
:/ -> <EMOTICON_SKEPTICAL_ANNOYED_UNEASY_HESITANT>
6360: 🥺
🥺 -> <EMOJI_PLEADING_FACE>
6360: 🥺
🥺 -> <EMOJI_PLEADING_FACE>
6363: 🥺
🥺 -> <EMOJI_PLEADING_FACE>
6363: 🥺
🥺 -> <EMOJI_PLEADING_FACE>
==Row 6367== :/
:/ -> <EMOTICON_SKEPTICAL_ANNOYED_UNEASY_HESITANT>
==Row 6368== :/
:/ -> <EMOTICON_SKEPTICAL_ANNOYED_UNEASY_HESITANT>
==Row 6368== :/
:/ -> <EMOTICON_SKEPTICAL_ANNOYED_UNEASY_HESITANT>
==Row 6451== :/
:/ -> <EMOTICON_SKEPTICAL_ANNOYED_UNEASY_HESITANT>
==Row 6493== :/
:/ -> <EMOTICON_SKEPTICAL_ANNOYED_UNEASY_HESITANT>
==Row 6541== :/
:/ -> <EMOTICON_SKEPTICAL_ANNOYED_UNEASY_HESITANT>
==Row 6613== :/
:/ -> <EMOTICON_SKEPTICAL_ANNOYED_UNEASY_HESITANT>
==Row 6637== :/
:/ -> <EMOTICON_SKEPTICAL_ANNOYED_UNEASY_HESITANT>
==Row 6638== :/
:/ -> <EMOTICON_SKEPTICAL_ANNOYED_UNEASY_HESITANT>
==Row 6643== :/
:/ -> <EMOTICON_SKEPTICAL_ANNOYED_UNEASY_HESITANT>
==Row 6644== :/
:/ -> <EMOTICON_SKEPTICAL_ANNOYED_UNEASY_HESITANT>
==Row 6645== ;)
;) -> <EMOTICON_WINK_SMIRK>
==Row 6817== :/
:/ -> <EMOTICON_SKEPTICAL_ANNOYED_UNEASY_HESITANT>
==Row 6823== :/
:/ -> <EMOTICON_SKEPTICAL_ANNOYED_UNEASY_HESITANT>
==Row 6877== :/
:/ -> <EMOTICON_SKEPTICAL_ANNOYED_UNEASY_HESITANT>
==Row 6878== :/
:/ -> <EMOTICON_SKEPTICAL_ANNOYED_UNEASY_HESITANT>
==Row 6895== :/
:/ -> <EMOTICON_SKEPTICAL_ANNOYED_UNEASY_HESITANT>
==Row 6913== :/
:/ -> <EMOTICON_SKEPTICAL_ANNOYED_UNEASY_HESITANT>
==Row 6914== :/
:/ -> <EMOTICON_SKEPTICAL_ANNOYED_UNEASY_HESITANT>
==Row 6955== :/
:/ -> <EMOTICON_SKEPTICAL_ANNOYED_UNEASY_HESITANT>
==Row 6996== :)
:) -> <EMOTICON_SMILEY>
==Row 6997== :)
:) -> <EMOTICON_SMILEY>
==Row 6997== :/
:/ -> <EMOTICON_SKEPTICAL_ANNOYED_UNEASY_HESITANT>
==Row 6998== :)
:) -> <EMOTICON_SMILEY>
==Row 6999== :)
:) -> <EMOTICON_SMILEY>
==Row 7000== :)
:) -> <EMOTICON_SMILEY>
==Row 7004== :/
:/ -> <EMOTICON_SKEPTICAL_ANNOYED_UNEASY_HESITANT>
7008: 🤣
🤣 -> <EMOJI_ROLLING_ON_THE_FLOOR_LAUGHING>
7008: 🤣
🤣 -> <EMOJI_ROLLING_ON_THE_FLOOR_LAUGHING>
7011: 🤣
🤣 -> <EMOJI_ROLLING_ON_THE_FLOOR_LAUGHING>
7011: 🤣
🤣 -> <EMOJI_ROLLING_ON_THE_FLOOR_LAUGHING>
7012: 🤣
🤣 -> <EMOJI_ROLLING_ON_THE_FLOOR_LAUGHING>
7012: 🤣
🤣 -> <EMOJI_ROLLING_ON_THE_FLOOR_LAUGHING>
==Row 7119== xp
xp -> <EMOTICON_PLAYFUL/CHEEKY_WITH_TONGUE>
==Row 7272== :D
:D -> <EMOTICON_BIG_GRIN>
==Row 7275== :D
:D -> <EMOTICON_BIG_GRIN>
==Row 7277== :D
:D -> <EMOTICON_BIG_GRIN>
==Row 7344== :(
:( -> <EMOTICON_FROWN_SAD>
==Row 7347== :(
:( -> <EMOTICON_FROWN_SAD>
==Row 7349== :(
:( -> <EMOTICON_FROWN_SAD>
==Row 7584== xp
xp -> <EMOTICON_PLAYFUL/CHEEKY_WITH_TONGUE>
==Row 7585== xp
xp -> <EMOTICON_PLAYFUL/CHEEKY_WITH_TONGUE>
==Row 7586== xp
xp -> <EMOTICON_PLAYFUL/CHEEKY_WITH_TONGUE>
==Row 7587== xp
xp -> <EMOTICON_PLAYFUL/CHEEKY_WITH_TONGUE>
==Row 7588== xp
xp -> <EMOTICON_PLAYFUL/CHEEKY_WITH_TONGUE>
==Row 7589== XP
XP -> <EMOTICON_PLAYFUL/CHEEKY_WITH_TONGUE>
==Row 7597== :/
:/ -> <EMOTICON_SKEPTICAL_ANNOYED_UNEASY_HESITANT>
7614: 🥳
🥳 -> <EMOJI_PARTYING_FACE>
7614: 🥰
🥰 -> <EMOJI_SMILING_FACE_WITH_HEARTS>
7617: 🥳
🥳 -> <EMOJI_PARTYING_FACE>
7617: 🥰
🥰 -> <EMOJI_SMILING_FACE_WITH_HEARTS>
==Row 7633== :/
:/ -> <EMOTICON_SKEPTICAL_ANNOYED_UNEASY_HESITANT>
==Row 7675== :/
:/ -> <EMOTICON_SKEPTICAL_ANNOYED_UNEASY_HESITANT>
==Row 7706== :/
:/ -> <EMOTICON_SKEPTICAL_ANNOYED_UNEASY_HESITANT>
7800: 🥰
🥰 -> <EMOJI_SMILING_FACE_WITH_HEARTS>
7803: 🥰
🥰 -> <EMOJI_SMILING_FACE_WITH_HEARTS>
==Row 7842== xD
xD -> <EMOTICON_LAUGHING>
==Row 7843== xD
xD -> <EMOTICON_LAUGHING>
==Row 7845== xD
xD -> <EMOTICON_LAUGHING>
==Row 7846== xD
xD -> <EMOTICON_LAUGHING>
==Row 7847== xD
xD -> <EMOTICON_LAUGHING>
7938: 🤩
🤩 -> <EMOJI_STAR-STRUCK>
7941: 🤩
🤩 -> <EMOJI_STAR-STRUCK>
==Row 7986== XD
XD -> <EMOTICON_LAUGHING>
==Row 7987== XD
XD -> <EMOTICON_LAUGHING>
==Row 7988== XD
XD -> <EMOTICON_LAUGHING>
==Row 7989== XD
XD -> <EMOTICON_LAUGHING>
==Row 7990== XD
XD -> <EMOTICON_LAUGHING>
==Row 7991== XD
XD -> <EMOTICON_LAUGHING>
==Row 8011== :/
:/ -> <EMOTICON_SKEPTICAL_ANNOYED_UNEASY_HESITANT>
8016: 🥰
🥰 -> <EMOJI_SMILING_FACE_WITH_HEARTS>
8016: 🥰
🥰 -> <EMOJI_SMILING_FACE_WITH_HEARTS>
8016: 🥰
🥰 -> <EMOJI_SMILING_FACE_WITH_HEARTS>
==Row 8280== :(
:( -> <EMOTICON_FROWN_SAD>
==Row 8283== :(
:( -> <EMOTICON_FROWN_SAD>
==Row 8285== :(
:( -> <EMOTICON_FROWN_SAD>
8322: ™
™ -> <EMOJI_TRADE_MARK>
8323: ™
™ -> <EMOJI_TRADE_MARK>
==Row 8323== :/
:/ -> <EMOTICON_SKEPTICAL_ANNOYED_UNEASY_HESITANT>
8324: ™
™ -> <EMOJI_TRADE_MARK>
==Row 8324== :/
:/ -> <EMOTICON_SKEPTICAL_ANNOYED_UNEASY_HESITANT>
==Row 8324== :/
:/ -> <EMOTICON_SKEPTICAL_ANNOYED_UNEASY_HESITANT>
8325: ™
™ -> <EMOJI_TRADE_MARK>
8430: 🥵
🥵 -> <EMOJI_HOT_FACE>
8433: 🥵
🥵 -> <EMOJI_HOT_FACE>
8454: 🥰
🥰 -> <EMOJI_SMILING_FACE_WITH_HEARTS>
8454: 🥰
🥰 -> <EMOJI_SMILING_FACE_WITH_HEARTS>
8454: 🥰
🥰 -> <EMOJI_SMILING_FACE_WITH_HEARTS>
8457: 🥰
🥰 -> <EMOJI_SMILING_FACE_WITH_HEARTS>
8457: 🥰
🥰 -> <EMOJI_SMILING_FACE_WITH_HEARTS>
8457: 🥰
🥰 -> <EMOJI_SMILING_FACE_WITH_HEARTS>
8622: 🤠
🤠 -> <EMOJI_COWBOY_HAT_FACE>
8625: 🤠
🤠 -> <EMOJI_COWBOY_HAT_FACE>
==Row 8647== :/
:/ -> <EMOTICON_SKEPTICAL_ANNOYED_UNEASY_HESITANT>
==Row 8648== :/
:/ -> <EMOTICON_SKEPTICAL_ANNOYED_UNEASY_HESITANT>
==Row 8653== :/
:/ -> <EMOTICON_SKEPTICAL_ANNOYED_UNEASY_HESITANT>
==Row 8803== :/

Bingxi: 
    This is for me to test whether my code for replacing emoji is working

In [16]:
df.iloc[576]

id                                                           2500
entity                                                Borderlands
sentiment                                              Irrelevant
text            Top 4 favourite games you say? 🤔. . Sea of Thi...
cleaned_text    [Top, 4, favourite, games, you, say, ?, <EMOJI...
Name: 576, dtype: object

In [17]:
df.head()

,id,entity,sentiment,text,cleaned_text
0,2401,Borderlands,Positive,im getting on borderlands and i will murder yo...,"[im, getting, on, <ENTITY>, and, i, will, murd..."
1,2401,Borderlands,Positive,I am coming to the borders and I will kill you...,"[I, am, coming, to, the, borders, and, I, will..."
2,2401,Borderlands,Positive,im getting on borderlands and i will kill you ...,"[im, getting, on, <ENTITY>, and, i, will, kill..."
3,2401,Borderlands,Positive,im coming on borderlands and i will murder you...,"[im, coming, on, <ENTITY>, and, i, will, murde..."
4,2401,Borderlands,Positive,im getting on borderlands 2 and i will murder ...,"[im, getting, on, <ENTITY>, 2, and, i, will, m..."

In [13]:
df.to_csv(OUT_CSV)