In [1]:
import emoji
import nltk
import numpy as np
import pandas as pd
import re

from nltk.tokenize import TweetTokenizer
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer

Change the path for the csv ***HERE*** accordingly to load/save

In [2]:
IN_CSV = "../../data/twitter_training.csv"
OUT_CSV = '../../data/output_file.csv'

TITLES = ["id", "entity", "sentiment", "text"]

In [3]:
df = pd.read_csv(IN_CSV, names=TITLES).astype(str)

In [4]:
df.head()

,id,entity,sentiment,text
0,2401,Borderlands,Positive,im getting on borderlands and i will murder yo...
1,2401,Borderlands,Positive,I am coming to the borders and I will kill you...
2,2401,Borderlands,Positive,im getting on borderlands and i will kill you ...
3,2401,Borderlands,Positive,im coming on borderlands and i will murder you...
4,2401,Borderlands,Positive,im getting on borderlands 2 and i will murder ...

In [5]:
tokenizer = TweetTokenizer()

Bingxi: Note for myself that twitter usernames are not case sensitive.

In [19]:
def preprocess(row):
    entity = row["entity"]
    text = row["text"]

    FLAG = re.I

    emoji_pattern = r"(\ud83c[d000-dfff]|\ud83d[d000-dfff]|\ud83e[d000-dfff])"

    url_pattern = r'(https?:\/\/)?(([\w\-]{1,63}\.)+[\w\-]{1,63})(\/[\w.\-]+)*([?=+%\w~\-.&]*)'
    entity_pattern = rf"@?{entity}"
    user_pattern = r"@\w+"
    repeated_pattern = r"(.)\1\1\1+"
    repeated_replace_pattern = r"\1\1\1"

    # Replaces emoji
    # emojis = re.findall(emoji_pattern, text)
    
    # if len(emojis) != 0:
    #     print(f"{row.name}: {emojis}")
    #     for e in emojis:
    #         if not emoji.is_emoji(e):
    #             continue
    #         e_meaning = emoji.demojize(e)[1:-1]
    #         e_replacement = f"<EMOJI_{e_meaning.upper()}>"
    #         print(f"{e} -> {e_replacement}")
    #         text = re.sub(rf"{e}", e_replacement, text)
    #     print("\n")


    # Concate if potential URL/Username
    text = re.sub(r"\s+\/(\s+)?", "/", text)
    text = re.sub(r"\@\s+", "@", text)

    # Replaces URL
    text = re.sub(url_pattern, '<URL>', text)

    # Replaces entity and other_user
    # text = re.sub(r"@ *")
    text = re.sub(entity_pattern, "<ENTITY>", text, flags=FLAG)
    text = re.sub(user_pattern, "<OTHER_USER>", text)

    # Raplaces repeated patterns
    text = re.sub(repeated_pattern, repeated_replace_pattern, text)
    
    tokens = tokenizer.tokenize(text)

    for token in tokens:
        if not emoji.is_emoji(token):
            continue

        print(f"{row.name}: {token}")
        e_meaning = emoji.demojize(token)[1:-1]
        e_replacement = f"<EMOJI_{e_meaning.upper()}>"
        print(f"{token} -> {e_replacement}")
        token = e_replacement
    
    return tokens

In [ ]:
df["cleaned_text"] = df.apply(preprocess, axis=1)

78: ‼
‼ -> <EMOJI_DOUBLE_EXCLAMATION_MARK>
81: ‼
‼ -> <EMOJI_DOUBLE_EXCLAMATION_MARK>
222: 1⃣
1⃣ -> <EMOJI_KEYCAP_1>
225: 1⃣
1⃣ -> <EMOJI_KEYCAP_1>
576: 🤔
🤔 -> <EMOJI_THINKING_FACE>
579: 🤔
🤔 -> <EMOJI_THINKING_FACE>
648: 🤔
🤔 -> <EMOJI_THINKING_FACE>
651: 🤔
🤔 -> <EMOJI_THINKING_FACE>
652: 🤔
🤔 -> <EMOJI_THINKING_FACE>
672: 🥰
🥰 -> <EMOJI_SMILING_FACE_WITH_HEARTS>
672: 🥰
🥰 -> <EMOJI_SMILING_FACE_WITH_HEARTS>
672: 🥰
🥰 -> <EMOJI_SMILING_FACE_WITH_HEARTS>
708: 🤞
🤞 -> <EMOJI_CROSSED_FINGERS>
711: 🤞
🤞 -> <EMOJI_CROSSED_FINGERS>
894: 🧨
🧨 -> <EMOJI_FIRECRACKER>
894: 🧨
🧨 -> <EMOJI_FIRECRACKER>
897: 🧨
🧨 -> <EMOJI_FIRECRACKER>
897: 🧨
🧨 -> <EMOJI_FIRECRACKER>
1074: 🧘
🧘 -> <EMOJI_PERSON_IN_LOTUS_POSITION>
1074: 🧘
🧘 -> <EMOJI_PERSON_IN_LOTUS_POSITION>
1077: 🧘
🧘 -> <EMOJI_PERSON_IN_LOTUS_POSITION>
1077: 🧘
🧘 -> <EMOJI_PERSON_IN_LOTUS_POSITION>
1078: 🧘
🧘 -> <EMOJI_PERSON_IN_LOTUS_POSITION>
1078: 🧘
🧘 -> <EMOJI_PERSON_IN_LOTUS_POSITION>
1128: 🤔
🤔 -> <EMOJI_THINKING_FACE>
1131: 🤔
🤔 -> <EMOJI_THINKING_FACE>
1272: 🤯
🤯 -> <EMOJI_EXPLODING_HEAD>
1275: 🤯
🤯 -> <EMOJI_EXPLODING_HEAD>
2232: 🤞
🤞 -> <EMOJI_CROSSED_FINGERS>
2235: 🤞
🤞 -> <EMOJI_CROSSED_FINGERS>
2484: 🤦
🤦 -> <EMOJI_PERSON_FACEPALMING>
2487: 🤦
🤦 -> <EMOJI_PERSON_FACEPALMING>
3450: 🤣
🤣 -> <EMOJI_ROLLING_ON_THE_FLOOR_LAUGHING>
3450: 🤦
🤦 -> <EMOJI_PERSON_FACEPALMING>
3453: 🤣
🤣 -> <EMOJI_ROLLING_ON_THE_FLOOR_LAUGHING>
3546: 🤩
🤩 -> <EMOJI_STAR-STRUCK>
3546: ‼
‼ -> <EMOJI_DOUBLE_EXCLAMATION_MARK>
3564: 🥺
🥺 -> <EMOJI_PLEADING_FACE>
3567: 🥺
🥺 -> <EMOJI_PLEADING_FACE>
3606: 🥺
🥺 -> <EMOJI_PLEADING_FACE>
3609: 🥺
🥺 -> <EMOJI_PLEADING_FACE>
3624: 🤔
🤔 -> <EMOJI_THINKING_FACE>
3888: 🥴
🥴 -> <EMOJI_WOOZY_FACE>
3891: 🥴
🥴 -> <EMOJI_WOOZY_FACE>
3942: 🤞
🤞 -> <EMOJI_CROSSED_FINGERS>
3945: 🤞
🤞 -> <EMOJI_CROSSED_FINGERS>
3946: 🤞
🤞 -> <EMOJI_CROSSED_FINGERS>
3948: 🥰
🥰 -> <EMOJI_SMILING_FACE_WITH_HEARTS>
3951: 🥰
🥰 -> <EMOJI_SMILING_FACE_WITH_HEARTS>
3952: 🥰
🥰 -> <EMOJI_SMILING_FACE_WITH_HEARTS>
4056: 🤢
🤢 -> <EMOJI_NAUSEATED_FACE>
4059: 🤢
🤢 -> <EMOJI_NAUSEATED_FACE>
4116: 🤩
🤩 -> <EMOJI_STAR-STRUCK>
4116: 🤩
🤩 -> <EMOJI_STAR-STRUCK>
4119: 🤩
🤩 -> <EMOJI_STAR-STRUCK>
4119: 🤩
🤩 -> <EMOJI_STAR-STRUCK>
4800: 🥳
🥳 -> <EMOJI_PARTYING_FACE>
4803: 🥳
🥳 -> <EMOJI_PARTYING_FACE>
5160: 🤦
🤦 -> <EMOJI_PERSON_FACEPALMING>
5163: 🤦
🤦 -> <EMOJI_PERSON_FACEPALMING>
5280: 🤔
🤔 -> <EMOJI_THINKING_FACE>
5283: 🤔
🤔 -> <EMOJI_THINKING_FACE>
5430: 🤟
🤟 -> <EMOJI_LOVE-YOU_GESTURE>
5430: 🤳
🤳 -> <EMOJI_SELFIE>
5430: 🤷
🤷 -> <EMOJI_PERSON_SHRUGGING>
5433: 🤟
🤟 -> <EMOJI_LOVE-YOU_GESTURE>
5433: 🤳
🤳 -> <EMOJI_SELFIE>
5433: 🤷
🤷 -> <EMOJI_PERSON_SHRUGGING>
5434: 🤟
🤟 -> <EMOJI_LOVE-YOU_GESTURE>
5434: 🤳
🤳 -> <EMOJI_SELFIE>
5434: 🤷
🤷 -> <EMOJI_PERSON_SHRUGGING>
5562: 🤣
🤣 -> <EMOJI_ROLLING_ON_THE_FLOOR_LAUGHING>
6132: 🥺
🥺 -> <EMOJI_PLEADING_FACE>
6135: 🥺
🥺 -> <EMOJI_PLEADING_FACE>
6360: 🥺
🥺 -> <EMOJI_PLEADING_FACE>
6360: 🥺
🥺 -> <EMOJI_PLEADING_FACE>
6363: 🥺
🥺 -> <EMOJI_PLEADING_FACE>
6363: 🥺
🥺 -> <EMOJI_PLEADING_FACE>
7008: 🤣
🤣 -> <EMOJI_ROLLING_ON_THE_FLOOR_LAUGHING>
7008: 🤣
🤣 -> <EMOJI_ROLLING_ON_THE_FLOOR_LAUGHING>
7011: 🤣
🤣 -> <EMOJI_ROLLING_ON_THE_FLOOR_LAUGHING>
7011: 🤣
🤣 -> <EMOJI_ROLLING_ON_THE_FLOOR_LAUGHING>
7012: 🤣
🤣 -> <EMOJI_ROLLING_ON_THE_FLOOR_LAUGHING>
7012: 🤣
🤣 -> <EMOJI_ROLLING_ON_THE_FLOOR_LAUGHING>
7614: 🥳
🥳 -> <EMOJI_PARTYING_FACE>
7614: 🥰
🥰 -> <EMOJI_SMILING_FACE_WITH_HEARTS>
7617: 🥳
🥳 -> <EMOJI_PARTYING_FACE>
7617: 🥰
🥰 -> <EMOJI_SMILING_FACE_WITH_HEARTS>
7800: 🥰
🥰 -> <EMOJI_SMILING_FACE_WITH_HEARTS>
7803: 🥰
🥰 -> <EMOJI_SMILING_FACE_WITH_HEARTS>
7938: 🤩
🤩 -> <EMOJI_STAR-STRUCK>
7941: 🤩
🤩 -> <EMOJI_STAR-STRUCK>
8016: 🥰
🥰 -> <EMOJI_SMILING_FACE_WITH_HEARTS>
8016: 🥰
🥰 -> <EMOJI_SMILING_FACE_WITH_HEARTS>
8016: 🥰
🥰 -> <EMOJI_SMILING_FACE_WITH_HEARTS>
8322: ™
™ -> <EMOJI_TRADE_MARK>
8323: ™
™ -> <EMOJI_TRADE_MARK>
8324: ™
™ -> <EMOJI_TRADE_MARK>
8325: ™
™ -> <EMOJI_TRADE_MARK>
8430: 🥵
🥵 -> <EMOJI_HOT_FACE>
8433: 🥵
🥵 -> <EMOJI_HOT_FACE>
8454: 🥰
🥰 -> <EMOJI_SMILING_FACE_WITH_HEARTS>
8454: 🥰
🥰 -> <EMOJI_SMILING_FACE_WITH_HEARTS>
8454: 🥰
🥰 -> <EMOJI_SMILING_FACE_WITH_HEARTS>
8457: 🥰
🥰 -> <EMOJI_SMILING_FACE_WITH_HEARTS>
8457: 🥰
🥰 -> <EMOJI_SMILING_FACE_WITH_HEARTS>
8457: 🥰
🥰 -> <EMOJI_SMILING_FACE_WITH_HEARTS>
8622: 🤠
🤠 -> <EMOJI_COWBOY_HAT_FACE>
8625: 🤠
🤠 -> <EMOJI_COWBOY_HAT_FACE>
8916: 🤠
🤠 -> <EMOJI_COWBOY_HAT_FACE>
9420: 🤣
🤣 -> <EMOJI_ROLLING_ON_THE_FLOOR_LAUGHING>
9420: 🤣
🤣 -> <EMOJI_ROLLING_ON_THE_FLOOR_LAUGHING>
9420: 🤣
🤣 -> <EMOJI_ROLLING_ON_THE_FLOOR_LAUGHING>
9444: 🤣
🤣 -> <EMOJI_ROLLING_ON_THE_FLOOR_LAUGHING>
9447: 🤣
🤣 -> <EMOJI_ROLLING_ON_THE_FLOOR_LAUGHING>
9822: 🤯
🤯 -> <EMOJI_EXPLODING_HEAD>
9825: 🤯
🤯 -> <EMOJI_EXPLODING_HEAD>
9834: 🥳
🥳 -> <EMOJI_PARTYING_FACE>
9837: 🥳
🥳 -> <EMOJI_PARTYING_FACE>
9964: ©
© -> <EMOJI_COPYRIGHT>
9972: 🪓
🪓 -> <EMOJI_AXE>
9975: 🪓
🪓 -> <EMOJI_AXE>
9978: 🤣
🤣 -> <EMOJI_ROLLING_ON_THE_FLOOR_LAUGHING>
9981: 🤣
🤣 -> <EMOJI_ROLLING_ON_THE_FLOOR_LAUGHING>
10014: 🤣
🤣 -> <EMOJI_ROLLING_ON_THE_FLOOR_LAUGHING>
10017: 🤣
🤣 -> <EMOJI_ROLLING_ON_THE_FLOOR_LAUGHING>
10152: 🤔
🤔 -> <EMOJI_THINKING_FACE>
10155: 🤔
🤔 -> <EMOJI_THINKING_FACE>
10338: 🥺
🥺 -> <EMOJI_PLEADING_FACE>
10341: 🥺
🥺 -> <EMOJI_PLEADING_FACE>
10584: 🦊
🦊 -> <EMOJI_FOX>
10650: 🤔
🤔 -> <EMOJI_THINKING_FACE>
10653: 🤔
🤔 -> <EMOJI_THINKING_FACE>
10836: 🤷
🤷 -> <EMOJI_PERSON_SHRUGGING>
11046: 🤔
🤔 -> <EMOJI_THINKING_FACE>
11049: 🤔
🤔 -> <EMOJI_THINKING_FACE>
11076: 🧐
🧐 -> <EMOJI_FACE_WITH_MONOCLE>
11079: 🧐
🧐 -> <EMOJI_FACE_WITH_MONOCLE>
11166: 🥳
🥳 -> <EMOJI_PARTYING_FACE>
11166: 🥳
🥳 -> <EMOJI_PARTYING_FACE>
11166: 🥳
🥳 -> <EMOJI_PARTYING_FACE>
11169: 🥳
🥳 -> <EMOJI_PARTYING_FACE>
11169: 🥳
🥳 -> <EMOJI_PARTYING_FACE>
11169: 🥳
🥳 -> <EMOJI_PARTYING_FACE>
11340: 🤣
🤣 -> <EMOJI_ROLLING_ON_THE_FLOOR_LAUGHING>
11340: 🤡
🤡 -> <EMOJI_CLOWN_FACE>
11340: 🤣
🤣 -> <EMOJI_ROLLING_ON_THE_FLOOR_LAUGHING>
11343: 🤣
🤣 -> <EMOJI_ROLLING_ON_THE_FLOOR_LAUGHING>
11343: 🤡
🤡 -> <EMOJI_CLOWN_FACE>
11343: 🤣
🤣 -> <EMOJI_ROLLING_ON_THE_FLOOR_LAUGHING>
11550: 🤯
🤯 -> <EMOJI_EXPLODING_HEAD>
11553: 🤯
🤯 -> <EMOJI_EXPLODING_HEAD>
11592: 🤣
🤣 -> <EMOJI_ROLLING_ON_THE_FLOOR_LAUGHING>
11595: 🤣
🤣 -> <EMOJI_ROLLING_ON_THE_FLOOR_LAUGHING>
11664: 🤣
🤣 -> <EMOJI_ROLLING_ON_THE_FLOOR_LAUGHING>
11667: 🤣
🤣 -> <EMOJI_ROLLING_ON_THE_FLOOR_LAUGHING>
11688: ‼
‼ -> <EMOJI_DOUBLE_EXCLAMATION_MARK>
11688: 🤦
🤦 -> <EMOJI_PERSON_FACEPALMING>
11691: ‼
‼ -> <EMOJI_DOUBLE_EXCLAMATION_MARK>
11691: 🤦
🤦 -> <EMOJI_PERSON_FACEPALMING>
11724: 🤔
🤔 -> <EMOJI_THINKING_FACE>
11727: 🤔
🤔 -> <EMOJI_THINKING_FACE>
11766: 🥰
🥰 -> <EMOJI_SMILING_FACE_WITH_HEARTS>
11769: 🥰
🥰 -> <EMOJI_SMILING_FACE_WITH_HEARTS>
11796: 🧢
🧢 -> <EMOJI_BILLED_CAP>
11796: 🧢
🧢 -> <EMOJI_BILLED_CAP>
11796: 🧢
🧢 -> <EMOJI_BILLED_CAP>
11799: 🧢
🧢 -> <EMOJI_BILLED_CAP>
11799: 🧢
🧢 -> <EMOJI_BILLED_CAP>
11799: 🧢
🧢 -> <EMOJI_BILLED_CAP>
11826: 🥺
🥺 -> <EMOJI_PLEADING_FACE>
11829: 🥺
🥺 -> <EMOJI_PLEADING_FACE>
11832: 🤯
🤯 -> <EMOJI_EXPLODING_HEAD>
11835: 🤯
🤯 -> <EMOJI_EXPLODING_HEAD>
12054: 🤡
🤡 -> <EMOJI_CLOWN_FACE>
12057: 🤡
🤡 -> <EMOJI_CLOWN_FACE>
12174: 🤦
🤦 -> <EMOJI_PERSON_FACEPALMING>
12177: 🤦
🤦 -> <EMOJI_PERSON_FACEPALMING>
12270: 🤣
🤣 -> <EMOJI_ROLLING_ON_THE_FLOOR_LAUGHING>
12273: 🤣
🤣 -> <EMOJI_ROLLING_ON_THE_FLOOR_LAUGHING>
12274: 🤣
🤣 -> <EMOJI_ROLLING_ON_THE_FLOOR_LAUGHING>
12378: 🤦
🤦 -> <EMOJI_PERSON_FACEPALMING>
12381: 🤦
🤦 -> <EMOJI_PERSON_FACEPALMING>
12396: 🤷
🤷 -> <EMOJI_PERSON_SHRUGGING>
12396: 🤷
🤷 -> <EMOJI_PERSON_SHRUGGING>
12399: 🤷
🤷 -> <EMOJI_PERSON_SHRUGGING>
12522: 🥰
🥰 -> <EMOJI_SMILING_FACE_WITH_HEARTS>
12522: 🥰
🥰 -> <EMOJI_SMILING_FACE_WITH_HEARTS>
12525: 🥰
🥰 -> <EMOJI_SMILING_FACE_WITH_HEARTS>
12525: 🥰
🥰 -> <EMOJI_SMILING_FACE_WITH_HEARTS>
12606: ‼
‼ -> <EMOJI_DOUBLE_EXCLAMATION_MARK>
12609: ‼
‼ -> <EMOJI_DOUBLE_EXCLAMATION_MARK>
12790: ©
© -> <EMOJI_COPYRIGHT>
12918: ‼
‼ -> <EMOJI_DOUBLE_EXCLAMATION_MARK>
12918: 🤣
🤣 -> <EMOJI_ROLLING_ON_THE_FLOOR_LAUGHING>
12921: ‼
‼ -> <EMOJI_DOUBLE_EXCLAMATION_MARK>
12921: 🤣
🤣 -> <EMOJI_ROLLING_ON_THE_FLOOR_LAUGHING>
13050: 🤣
🤣 -> <EMOJI_ROLLING_ON_THE_FLOOR_LAUGHING>
13053: 🤣
🤣 -> <EMOJI_ROLLING_ON_THE_FLOOR_LAUGHING>
13080: 🤣
🤣 -> <EMOJI_ROLLING_ON_THE_FLOOR_LAUGHING>
13083: 🤣
🤣 -> <EMOJI_ROLLING_ON_THE_FLOOR_LAUGHING>
13206: 🥺
🥺 -> <EMOJI_PLEADING_FACE>
13206: 🥺
🥺 -> <EMOJI_PLEADING_FACE>
13206: 🥺
🥺 -> <EMOJI_PLEADING_FACE>
13209: 🥺
🥺 -> <EMOJI_PLEADING_FACE>
13209: 🥺
🥺 -> <EMOJI_PLEADING_FACE>
13209: 🥺
🥺 -> <EMOJI_PLEADING_FACE>
13254: ‼
‼ -> <EMOJI_DOUBLE_EXCLAMATION_MARK>
13257: ‼
‼ -> <EMOJI_DOUBLE_EXCLAMATION_MARK>
13344: 🤣
🤣 -> <EMOJI_ROLLING_ON_THE_FLOOR_LAUGHING>
13347: 🤣
🤣 -> <EMOJI_ROLLING_ON_THE_FLOOR_LAUGHING>
13542: 🤔
🤔 -> <EMOJI_THINKING_FACE>
13545: 🤔
🤔 -> <EMOJI_THINKING_FACE>
13554: 🤦
🤦 -> <EMOJI_PERSON_FACEPALMING>
13557: 🤦
🤦 -> <EMOJI_PERSON_FACEPALMING>
13569: 🙂
🙂 -> <EMOJI_SLIGHTLY_SMILING_FACE>
13614: 🤬
🤬 -> <EMOJI_FACE_WITH_SYMBOLS_ON_MOUTH>
13617: 🤬
🤬 -> <EMOJI_FACE_WITH_SYMBOLS_ON_MOUTH>
13620: 🤡
🤡 -> <EMOJI_CLOWN_FACE>
13623: 🤡
🤡 -> <EMOJI_CLOWN_FACE>
13626: 🤦
🤦 -> <EMOJI_PERSON_FACEPALMING>
13629: 🤦
🤦 -> <EMOJI_PERSON_FACEPALMING>
13812: ⌚
⌚ -> <EMOJI_WATCH>
13812: ⌚
⌚ -> <EMOJI_WATCH>
13815: ⌚
⌚ -> <EMOJI_WATCH>
13815: ⌚
⌚ -> <EMOJI_WATCH>
14406: 🥺
🥺 -> <EMOJI_PLEADING_FACE>
14406: 🥺
🥺 -> <EMOJI_PLEADING_FACE>
14430: 🤑
🤑 -> <EMOJI_MONEY-MOUTH_FACE>
14433: 🤑
🤑 -> <EMOJI_MONEY-MOUTH_FACE>
14496: 🤔
🤔 -> <EMOJI_THINKING_FACE>
14499: 🤔
🤔 -> <EMOJI_THINKING_FACE>
15378: 🥳
🥳 -> <EMOJI_PARTYING_FACE>
15381: 🥳
🥳 -> <EMOJI_PARTYING_FACE>
15528: 🥳
🥳 -> <EMOJI_PARTYING_FACE>
15531: 🥳
🥳 -> <EMOJI_PARTYING_FACE>
15546: 🤣
🤣 -> <EMOJI_ROLLING_ON_THE_FLOOR_LAUGHING>
15546: 🤣
🤣 -> <EMOJI_ROLLING_ON_THE_FLOOR_LAUGHING>
15546: 🤣
🤣 -> <EMOJI_ROLLING_ON_THE_FLOOR_LAUGHING>
15549: 🤣
🤣 -> <EMOJI_ROLLING_ON_THE_FLOOR_LAUGHING>
15549: 🤣
🤣 -> <EMOJI_ROLLING_ON_THE_FLOOR_LAUGHING>
15549: 🤣
🤣 -> <EMOJI_ROLLING_ON_THE_FLOOR_LAUGHING>
15774: 🤔
🤔 -> <EMOJI_THINKING_FACE>
16194: 🥰
🥰 -> <EMOJI_SMILING_FACE_WITH_HEARTS>
16197: 🥰
🥰 -> <EMOJI_SMILING_FACE_WITH_HEARTS>
16380: 🥺
🥺 -> <EMOJI_PLEADING_FACE>
16380: 🥺
🥺 -> <EMOJI_PLEADING_FACE>
16380: 🥺
🥺 -> <EMOJI_PLEADING_FACE>
16383: 🥺
🥺 -> <EMOJI_PLEADING_FACE>
16383: 🥺
🥺 -> <EMOJI_PLEADING_FACE>
16383: 🥺
🥺 -> <EMOJI_PLEADING_FACE>
16392: 🥺
🥺 -> <EMOJI_PLEADING_FACE>
16398: 🤑
🤑 -> <EMOJI_MONEY-MOUTH_FACE>
16434: 🤨
🤨 -> <EMOJI_FACE_WITH_RAISED_EYEBROW>
16437: 🤨
🤨 -> <EMOJI_FACE_WITH_RAISED_EYEBROW>
16482: 🤓
🤓 -> <EMOJI_NERD_FACE>
16482: 🤔
🤔 -> <EMOJI_THINKING_FACE>
16485: 🤓
🤓 -> <EMOJI_NERD_FACE>
16485: 🤔
🤔 -> <EMOJI_THINKING_FACE>
16512: 🤦
🤦 -> <EMOJI_PERSON_FACEPALMING>
16515: 🤦
🤦 -> <EMOJI_PERSON_FACEPALMING>
16554: 🤣
🤣 -> <EMOJI_ROLLING_ON_THE_FLOOR_LAUGHING>
16554: 🤣
🤣 -> <EMOJI_ROLLING_ON_THE_FLOOR_LAUGHING>
16554: 🤣
🤣 -> <EMOJI_ROLLING_ON_THE_FLOOR_LAUGHING>
16662: 🧹
🧹 -> <EMOJI_BROOM>
16668: 🤤
🤤 -> <EMOJI_DROOLING_FACE>
16998: 🤯
🤯 -> <EMOJI_EXPLODING_HEAD>
17001: 🤯
🤯 -> <EMOJI_EXPLODING_HEAD>
17010: 🤩
🤩 -> <EMOJI_STAR-STRUCK>
17013: 🤩
🤩 -> <EMOJI_STAR-STRUCK>
17082: 🥳
🥳 -> <EMOJI_PARTYING_FACE>
17085: 🥳
🥳 -> <EMOJI_PARTYING_FACE>
17172: 🤬
🤬 -> <EMOJI_FACE_WITH_SYMBOLS_ON_MOUTH>
17175: 🤬
🤬 -> <EMOJI_FACE_WITH_SYMBOLS_ON_MOUTH>
17352: 🥴
🥴 -> <EMOJI_WOOZY_FACE>
17352: 🤪
🤪 -> <EMOJI_ZANY_FACE>
17355: 🥴
🥴 -> <EMOJI_WOOZY_FACE>
17355: 🤪
🤪 -> <EMOJI_ZANY_FACE>
17652: 🤔
🤔 -> <EMOJI_THINKING_FACE>
17652: 🤫
🤫 -> <EMOJI_SHUSHING_FACE>
17898: 🤟
🤟 -> <EMOJI_LOVE-YOU_GESTURE>
17901: 🤟
🤟 -> <EMOJI_LOVE-YOU_GESTURE>
18048: 🤣
🤣 -> <EMOJI_ROLLING_ON_THE_FLOOR_LAUGHING>
18048: 🤣
🤣 -> <EMOJI_ROLLING_ON_THE_FLOOR_LAUGHING>
18048: 🤣
🤣 -> <EMOJI_ROLLING_ON_THE_FLOOR_LAUGHING>
18051: 🤣
🤣 -> <EMOJI_ROLLING_ON_THE_FLOOR_LAUGHING>
18051: 🤣
🤣 -> <EMOJI_ROLLING_ON_THE_FLOOR_LAUGHING>
18051: 🤣
🤣 -> <EMOJI_ROLLING_ON_THE_FLOOR_LAUGHING>
18060: 🤷
🤷 -> <EMOJI_PERSON_SHRUGGING>
18063: 🤷
🤷 -> <EMOJI_PERSON_SHRUGGING>
18216: 🤷
🤷 -> <EMOJI_PERSON_SHRUGGING>
18348: 🤣
🤣 -> <EMOJI_ROLLING_ON_THE_FLOOR_LAUGHING>
18348: 🤣
🤣 -> <EMOJI_ROLLING_ON_THE_FLOOR_LAUGHING>
18366: 🤣
🤣 -> <EMOJI_ROLLING_ON_THE_FLOOR_LAUGHING>
18366: 🤣
🤣 -> <EMOJI_ROLLING_ON_THE_FLOOR_LAUGHING>
18366: 🤣
🤣 -> <EMOJI_ROLLING_ON_THE_FLOOR_LAUGHING>
18369: 🤣
🤣 -> <EMOJI_ROLLING_ON_THE_FLOOR_LAUGHING>
18369: 🤣
🤣 -> <EMOJI_ROLLING_ON_THE_FLOOR_LAUGHING>
18369: 🤣
🤣 -> <EMOJI_ROLLING_ON_THE_FLOOR_LAUGHING>
18420: 🤩
🤩 -> <EMOJI_STAR-STRUCK>
18423: 🤩
🤩 -> <EMOJI_STAR-STRUCK>
18426: 🤣
🤣 -> <EMOJI_ROLLING_ON_THE_FLOOR_LAUGHING>
18426: 🤣
🤣 -> <EMOJI_ROLLING_ON_THE_FLOOR_LAUGHING>
18426: 🤣
🤣 -> <EMOJI_ROLLING_ON_THE_FLOOR_LAUGHING>
18429: 🤣
🤣 -> <EMOJI_ROLLING_ON_THE_FLOOR_LAUGHING>
18429: 🤣
🤣 -> <EMOJI_ROLLING_ON_THE_FLOOR_LAUGHING>
18429: 🤣
🤣 -> <EMOJI_ROLLING_ON_THE_FLOOR_LAUGHING>
18432: 🤷
🤷 -> <EMOJI_PERSON_SHRUGGING>
18435: 🤷
🤷 -> <EMOJI_PERSON_SHRUGGING>
18462: ‼
‼ -> <EMOJI_DOUBLE_EXCLAMATION_MARK>
18462: ‼
‼ -> <EMOJI_DOUBLE_EXCLAMATION_MARK>
18462: ‼
‼ -> <EMOJI_DOUBLE_EXCLAMATION_MARK>
18465: ‼
‼ -> <EMOJI_DOUBLE_EXCLAMATION_MARK>
18465: ‼
‼ -> <EMOJI_DOUBLE_EXCLAMATION_MARK>
18468: 🤦
🤦 -> <EMOJI_PERSON_FACEPALMING>
18471: 🤦
🤦 -> <EMOJI_PERSON_FACEPALMING>
18480: 🥴
🥴 -> <EMOJI_WOOZY_FACE>
18483: 🥴
🥴 -> <EMOJI_WOOZY_FACE>
18484: 🥴
🥴 -> <EMOJI_WOOZY_FACE>
18540: 🧐
🧐 -> <EMOJI_FACE_WITH_MONOCLE>
18543: 🧐
🧐 -> <EMOJI_FACE_WITH_MONOCLE>
18768: ™
™ -> <EMOJI_TRADE_MARK>
18771: ™
™ -> <EMOJI_TRADE_MARK>
18804: 🤡
🤡 -> <EMOJI_CLOWN_FACE>
18807: 🤡
🤡 -> <EMOJI_CLOWN_FACE>
18816: 🤣
🤣 -> <EMOJI_ROLLING_ON_THE_FLOOR_LAUGHING>
18816: 🤣
🤣 -> <EMOJI_ROLLING_ON_THE_FLOOR_LAUGHING>
18816: 🤣
🤣 -> <EMOJI_ROLLING_ON_THE_FLOOR_LAUGHING>
18819: 🤣
🤣 -> <EMOJI_ROLLING_ON_THE_FLOOR_LAUGHING>
18819: 🤣
🤣 -> <EMOJI_ROLLING_ON_THE_FLOOR_LAUGHING>
18819: 🤣
🤣 -> <EMOJI_ROLLING_ON_THE_FLOOR_LAUGHING>
18924: 🤬
🤬 -> <EMOJI_FACE_WITH_SYMBOLS_ON_MOUTH>
18927: 🤬
🤬 -> <EMOJI_FACE_WITH_SYMBOLS_ON_MOUTH>
18954: 🥖
🥖 -> <EMOJI_BAGUETTE_BREAD>
18957: 🥖
🥖 -> <EMOJI_BAGUETTE_BREAD>
19080: 🤣
🤣 -> <EMOJI_ROLLING_ON_THE_FLOOR_LAUGHING>
19083: 🤣
🤣 -> <EMOJI_ROLLING_ON_THE_FLOOR_LAUGHING>
19494: 🤪
🤪 -> <EMOJI_ZANY_FACE>
19554: 🧐
🧐 -> <EMOJI_FACE_WITH_MONOCLE>
19554: 🤔
🤔 -> <EMOJI_THINKING_FACE>
19557: 🧐
🧐 -> <EMOJI_FACE_WITH_MONOCLE>
19680: 🪓
🪓 -> <EMOJI_AXE>
19683: 🪓
🪓 -> <EMOJI_AXE>
19725: ®
® -> <EMOJI_REGISTERED>
19830: 🤣
🤣 -> <EMOJI_ROLLING_ON_THE_FLOOR_LAUGHING>
19830: 🤣
🤣 -> <EMOJI_ROLLING_ON_THE_FLOOR_LAUGHING>
19833: 🤣
🤣 -> <EMOJI_ROLLING_ON_THE_FLOOR_LAUGHING>
19833: 🤣
🤣 -> <EMOJI_ROLLING_ON_THE_FLOOR_LAUGHING>
19929: ©
© -> <EMOJI_COPYRIGHT>
20112: 🦊
🦊 -> <EMOJI_FOX>
20115: 🦊
🦊 -> <EMOJI_FOX>
20316: 🧝
🧝 -> <EMOJI_ELF>
20319: 🧝
🧝 -> <EMOJI_ELF>
20466: 🥺
🥺 -> <EMOJI_PLEADING_FACE>
20469: 🥺
🥺 -> <EMOJI_PLEADING_FACE>
20514: 🥰
🥰 -> <EMOJI_SMILING_FACE_WITH_HEARTS>
20664: 🤔
🤔 -> <EMOJI_THINKING_FACE>
20667: 🤔
🤔 -> <EMOJI_THINKING_FACE>
21096: 🤩
🤩 -> <EMOJI_STAR-STRUCK>
21096: 🤩
🤩 -> <EMOJI_STAR-STRUCK>
21270: 🥺
🥺 -> <EMOJI_PLEADING_FACE>
21273: 🥺
🥺 -> <EMOJI_PLEADING_FACE>
21402: 🥇
🥇 -> <EMOJI_1ST_PLACE_MEDAL>
21474: 🥰
🥰 -> <EMOJI_SMILING_FACE_WITH_HEARTS>
22326: 🤳
🤳 -> <EMOJI_SELFIE>
22326: 🤩
🤩 -> <EMOJI_STAR-STRUCK>
22329: 🤳
🤳 -> <EMOJI_SELFIE>
22329: 🤩
🤩 -> <EMOJI_STAR-STRUCK>
22330: 🤳
🤳 -> <EMOJI_SELFIE>
22330: 🤩
🤩 -> <EMOJI_STAR-STRUCK>
22614: 1⃣
1⃣ -> <EMOJI_KEYCAP_1>
22614: 2⃣
2⃣ -> <EMOJI_KEYCAP_2>
22614: 3⃣
3⃣ -> <EMOJI_KEYCAP_3>
22614: 4⃣
4⃣ -> <EMOJI_KEYCAP_4>
22614: 5⃣
5⃣ -> <EMOJI_KEYCAP_5>
22614: 6⃣
6⃣ -> <EMOJI_KEYCAP_6>
22614: 1⃣
1⃣ -> <EMOJI_KEYCAP_1>
22614: 2⃣
2⃣ -> <EMOJI_KEYCAP_2>
22614: 3⃣
3⃣ -> <EMOJI_KEYCAP_3>
22614: 4⃣
4⃣ -> <EMOJI_KEYCAP_4>
22614: 5⃣
5⃣ -> <EMOJI_KEYCAP_5>
22614: 6⃣
6⃣ -> <EMOJI_KEYCAP_6>
22617: 1⃣
1⃣ -> <EMOJI_KEYCAP_1>
22617: 2⃣
2⃣ -> <EMOJI_KEYCAP_2>
22617: 3⃣
3⃣ -> <EMOJI_KEYCAP_3>
22617: 4⃣
4⃣ -> <EMOJI_KEYCAP_4>
22617: 5⃣
5⃣ -> <EMOJI_KEYCAP_5>
22617: 6⃣
6⃣ -> <EMOJI_KEYCAP_6>
22617: 1⃣
1⃣ -> <EMOJI_KEYCAP_1>
22617: 2⃣
2⃣ -> <EMOJI_KEYCAP_2>
22617: 3⃣
3⃣ -> <EMOJI_KEYCAP_3>
22617: 4⃣
4⃣ -> <EMOJI_KEYCAP_4>
22617: 5⃣
5⃣ -> <EMOJI_KEYCAP_5>
22617: 6⃣
6⃣ -> <EMOJI_KEYCAP_6>
22618: 1⃣
1⃣ -> <EMOJI_KEYCAP_1>
22618: 2⃣
2⃣ -> <EMOJI_KEYCAP_2>
22618: 3⃣
3⃣ -> <EMOJI_KEYCAP_3>
22618: 4⃣
4⃣ -> <EMOJI_KEYCAP_4>
22618: 5⃣
5⃣ -> <EMOJI_KEYCAP_5>
22618: 6⃣
6⃣ -> <EMOJI_KEYCAP_6>
22618: 1⃣
1⃣ -> <EMOJI_KEYCAP_1>
22618: 2⃣
2⃣ -> <EMOJI_KEYCAP_2>
22618: 3⃣
3⃣ -> <EMOJI_KEYCAP_3>
22618: 4⃣
4⃣ -> <EMOJI_KEYCAP_4>
22618: 5⃣
5⃣ -> <EMOJI_KEYCAP_5>
22618: 6⃣
6⃣ -> <EMOJI_KEYCAP_6>
22668: 🥄
🥄 -> <EMOJI_SPOON>
22671: 🥄
🥄 -> <EMOJI_SPOON>
22672: 🥄
🥄 -> <EMOJI_SPOON>
22728: ™
™ -> <EMOJI_TRADE_MARK>
22729: ™
™ -> <EMOJI_TRADE_MARK>
22730: ™
™ -> <EMOJI_TRADE_MARK>
22731: ™
™ -> <EMOJI_TRADE_MARK>
22758: 🤯
🤯 -> <EMOJI_EXPLODING_HEAD>
22782: 🤧
🤧 -> <EMOJI_SNEEZING_FACE>
22785: 🤧
🤧 -> <EMOJI_SNEEZING_FACE>
22812: 🤣
🤣 -> <EMOJI_ROLLING_ON_THE_FLOOR_LAUGHING>
22815: 🤣
🤣 -> <EMOJI_ROLLING_ON_THE_FLOOR_LAUGHING>
22860: 🦊
🦊 -> <EMOJI_FOX>
22863: 🦊
🦊 -> <EMOJI_FOX>
22980: 🥩
🥩 -> <EMOJI_CUT_OF_MEAT>
22983: 🥩
🥩 -> <EMOJI_CUT_OF_MEAT>
22984: 🥩
🥩 -> <EMOJI_CUT_OF_MEAT>
23103: 🙂
🙂 -> <EMOJI_SLIGHTLY_SMILING_FACE>
23268: 🤣
🤣 -> <EMOJI_ROLLING_ON_THE_FLOOR_LAUGHING>
23271: 🤣
🤣 -> <EMOJI_ROLLING_ON_THE_FLOOR_LAUGHING>
23298: 🤛
🤛 -> <EMOJI_LEFT-FACING_FIST>
23301: 🤛
🤛 -> <EMOJI_LEFT-FACING_FIST>
23334: 🥵
🥵 -> <EMOJI_HOT_FACE>
23337: 🥵
🥵 -> <EMOJI_HOT_FACE>
23358: 🥴
🥴 -> <EMOJI_WOOZY_FACE>
23358: 🥴
🥴 -> <EMOJI_WOOZY_FACE>
23358: 🤣
🤣 -> <EMOJI_ROLLING_ON_THE_FLOOR_LAUGHING>
23358: 🤣
🤣 -> <EMOJI_ROLLING_ON_THE_FLOOR_LAUGHING>
23358: 🤣
🤣 -> <EMOJI_ROLLING_ON_THE_FLOOR_LAUGHING>
23466: 🤦
🤦 -> <EMOJI_PERSON_FACEPALMING>
23469: 🤦
🤦 -> <EMOJI_PERSON_FACEPALMING>
23478: 🤗
🤗 -> <EMOJI_SMILING_FACE_WITH_OPEN_HANDS>
23478: 🤩
🤩 -> <EMOJI_STAR-STRUCK>
23481: 🤗
🤗 -> <EMOJI_SMILING_FACE_WITH_OPEN_HANDS>
23481: 🤩
🤩 -> <EMOJI_STAR-STRUCK>
23565: ©
© -> <EMOJI_COPYRIGHT>
23574: 3⃣
3⃣ -> <EMOJI_KEYCAP_3>
23580: 🤩
🤩 -> <EMOJI_STAR-STRUCK>
23580: 🥳
🥳 -> <EMOJI_PARTYING_FACE>
23583: 🤩
🤩 -> <EMOJI_STAR-STRUCK>
23583: 🥳
🥳 -> <EMOJI_PARTYING_FACE>
23584: 🤩
🤩 -> <EMOJI_STAR-STRUCK>
23584: 🥳
🥳 -> <EMOJI_PARTYING_FACE>
23694: 🤣
🤣 -> <EMOJI_ROLLING_ON_THE_FLOOR_LAUGHING>
23694: 🤣
🤣 -> <EMOJI_ROLLING_ON_THE_FLOOR_LAUGHING>
23694: 🤣
🤣 -> <EMOJI_ROLLING_ON_THE_FLOOR_LAUGHING>
23697: 🤣
🤣 -> <EMOJI_ROLLING_ON_THE_FLOOR_LAUGHING>
23697: 🤣
🤣 -> <EMOJI_ROLLING_ON_THE_FLOOR_LAUGHING>
23697: 🤣
🤣 -> <EMOJI_ROLLING_ON_THE_FLOOR_LAUGHING>
23832: 🥴
🥴 -> <EMOJI_WOOZY_FACE>
23835: 🥴
🥴 -> <EMOJI_WOOZY_FACE>
23970: 🤦
🤦 -> <EMOJI_PERSON_FACEPALMING>
23973: 🤦
🤦 -> <EMOJI_PERSON_FACEPALMING>
23974: 🤦
🤦 -> <EMOJI_PERSON_FACEPALMING>
24288: 🤢
🤢 -> <EMOJI_NAUSEATED_FACE>
24288: 🤢
🤢 -> <EMOJI_NAUSEATED_FACE>
24288: 🤢
🤢 -> <EMOJI_NAUSEATED_FACE>
24291: 🤢
🤢 -> <EMOJI_NAUSEATED_FACE>
24291: 🤢
🤢 -> <EMOJI_NAUSEATED_FACE>
24291: 🤢
🤢 -> <EMOJI_NAUSEATED_FACE>
24360: 🤔
🤔 -> <EMOJI_THINKING_FACE>
24363: 🤔
🤔 -> <EMOJI_THINKING_FACE>
24504: 🤗
🤗 -> <EMOJI_SMILING_FACE_WITH_OPEN_HANDS>
24504: 🤣
🤣 -> <EMOJI_ROLLING_ON_THE_FLOOR_LAUGHING>
25026: 🤓
🤓 -> <EMOJI_NERD_FACE>
25029: 🤓
🤓 -> <EMOJI_NERD_FACE>
25030: 🤓
🤓 -> <EMOJI_NERD_FACE>
25086: 🥺
🥺 -> <EMOJI_PLEADING_FACE>
25224: 🥰
🥰 -> <EMOJI_SMILING_FACE_WITH_HEARTS>
25224: 🥰
🥰 -> <EMOJI_SMILING_FACE_WITH_HEARTS>
25227: 🥰
🥰 -> <EMOJI_SMILING_FACE_WITH_HEARTS>
25227: 🥰
🥰 -> <EMOJI_SMILING_FACE_WITH_HEARTS>
25228: 🥰
🥰 -> <EMOJI_SMILING_FACE_WITH_HEARTS>
25228: 🥰
🥰 -> <EMOJI_SMILING_FACE_WITH_HEARTS>
25260: 🤣
🤣 -> <EMOJI_ROLLING_ON_THE_FLOOR_LAUGHING>
25260: 🤣
🤣 -> <EMOJI_ROLLING_ON_THE_FLOOR_LAUGHING>
25263: 🤣
🤣 -> <EMOJI_ROLLING_ON_THE_FLOOR_LAUGHING>
25263: 🤣
🤣 -> <EMOJI_ROLLING_ON_THE_FLOOR_LAUGHING>
25264: 🤣
🤣 -> <EMOJI_ROLLING_ON_THE_FLOOR_LAUGHING>
25264: 🤣
🤣 -> <EMOJI_ROLLING_ON_THE_FLOOR_LAUGHING>
25542: 🤨
🤨 -> <EMOJI_FACE_WITH_RAISED_EYEBROW>
25545: 🤨
🤨 -> <EMOJI_FACE_WITH_RAISED_EYEBROW>
25797: ©
© -> <EMOJI_COPYRIGHT>
26028: 🤣
🤣 -> <EMOJI_ROLLING_ON_THE_FLOOR_LAUGHING>
26028: 🤣
🤣 -> <EMOJI_ROLLING_ON_THE_FLOOR_LAUGHING>
26028: 🤣
🤣 -> <EMOJI_ROLLING_ON_THE_FLOOR_LAUGHING>
26031: 🤣
🤣 -> <EMOJI_ROLLING_ON_THE_FLOOR_LAUGHING>
26031: 🤣
🤣 -> <EMOJI_ROLLING_ON_THE_FLOOR_LAUGHING>
26031: 🤣
🤣 -> <EMOJI_ROLLING_ON_THE_FLOOR_LAUGHING>
26280: 🥺
🥺 -> <EMOJI_PLEADING_FACE>
26283: 🥺
🥺 -> <EMOJI_PLEADING_FACE>
26478: 🥳
🥳 -> <EMOJI_PARTYING_FACE>
26850: 🤷
🤷 -> <EMOJI_PERSON_SHRUGGING>
26853: 🤷

Bingxi: 
    This is for me to test whether my code for replacing emoji is working, 
    new implementation using "emoji" package is testing

In [13]:
df.iloc[576]

id                                                           2500
entity                                                Borderlands
sentiment                                              Irrelevant
text            Top 4 favourite games you say? 🤔. . Sea of Thi...
cleaned_text    [Top, 4, favourite, games, you, say, ?, 🤔, . ....
Name: 576, dtype: object

In [14]:
df.head()

,id,entity,sentiment,text,cleaned_text
0,2401,Borderlands,Positive,im getting on borderlands and i will murder yo...,"[im, getting, on, <ENTITY>, and, i, will, murd..."
1,2401,Borderlands,Positive,I am coming to the borders and I will kill you...,"[I, am, coming, to, the, borders, and, I, will..."
2,2401,Borderlands,Positive,im getting on borderlands and i will kill you ...,"[im, getting, on, <ENTITY>, and, i, will, kill..."
3,2401,Borderlands,Positive,im coming on borderlands and i will murder you...,"[im, coming, on, <ENTITY>, and, i, will, murde..."
4,2401,Borderlands,Positive,im getting on borderlands 2 and i will murder ...,"[im, getting, on, <ENTITY>, 2, and, i, will, m..."

In [15]:
df.to_csv(OUT_CSV)